<?php
/**
 * (c) shopware AG <info@shopware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'billingaddress' => [
            'id' => 2,
            'company' => 'B2B',
            'department' => 'Einkauf',
            'salutation' => 'mr',
            'firstname' => 'Händler',
            'title' => null,
            'lastname' => 'Kundengruppe-Netto',
            'street' => 'Musterweg 1',
            'zipcode' => '55555',
            'city' => 'Musterstadt',
            'phone' => '012345 / 6789',
            'vatId' => null,
            'additionalAddressLine1' => null,
            'additionalAddressLine2' => null,
            'countryId' => 2,
            'stateId' => 3,
            'customer' => [
                    'id' => 2,
                ],
            'country' => [
                    'id' => 2,
                ],
            'state' => [
                    'id' => 3,
                ],
            'userID' => 2,
            'countryID' => 2,
            'stateID' => 3,
            'ustid' => null,
            'additional_address_line1' => null,
            'additional_address_line2' => null,
            'attributes' => [
                ],
        ],
    'additional' => [
            'country' => [
                    'id' => 2,
                    'countryname' => 'Deutschland',
                    'countryiso' => 'DE',
                    'areaID' => 1,
                    'countryen' => 'GERMANY',
                    'position' => 1,
                    'notice' => '',
                    'taxfree' => 0,
                    'taxfree_ustid' => 0,
                    'taxfree_ustid_checked' => 0,
                    'active' => 1,
                    'iso3' => 'DEU',
                    'display_state_in_registration' => 0,
                    'force_state_in_registration' => 0,
                    'allow_shipping' => 1,
                    'countryarea' => 'deutschland',
                ],
            'state' => [
                    'id' => 3,
                    'countryID' => 2,
                    'name' => 'Nordrhein-Westfalen',
                    'shortcode' => 'NW',
                    'position' => 0,
                    'active' => 1,
                    'statename' => 'Nordrhein-Westfalen',
                ],
            'user' => [
                    'id' => 2,
                    'password' => '$2y$10$87mlTWk2QprhhfOYuYM5HegrqK6UDfepdW.3sVutKHnSFQbHifGH6',
                    'encoder' => 'bcrypt',
                    'email' => 'mustermann@b2b.de',
                    'active' => 1,
                    'accountmode' => 0,
                    'confirmationkey' => '',
                    'paymentID' => 7,
                    'doubleOptinRegister' => 0,
                    'doubleOptinEmailSentDate' => null,
                    'doubleOptinConfirmDate' => null,
                    'firstlogin' => '2012-08-30',
                    'lastlogin' => '2022-04-12 11:53:46',
                    'sessionID' => '0c051221284ee8d67d238ace273f5987',
                    'newsletter' => 0,
                    'validation' => '0',
                    'affiliate' => 0,
                    'customergroup' => 'H',
                    'paymentpreset' => 4,
                    'language' => '1',
                    'subshopID' => 1,
                    'referer' => '',
                    'pricegroupID' => null,
                    'internalcomment' => '',
                    'failedlogins' => 0,
                    'lockeduntil' => null,
                    'default_billing_address_id' => 2,
                    'default_shipping_address_id' => 4,
                    'title' => null,
                    'salutation' => 'mr',
                    'firstname' => 'Händler',
                    'lastname' => 'Kundengruppe-Netto',
                    'birthday' => null,
                    'customernumber' => '20003',
                    'login_token' => 'c6fa799d-72f6-4b01-b7f0-d40017299271.1',
                    'changed' => null,
                    'password_change_date' => '2022-04-12 08:24:11',
                    'register_opt_in_id' => null,
                ],
            'countryShipping' => [
                    'id' => 2,
                    'countryname' => 'Deutschland',
                    'countryiso' => 'DE',
                    'areaID' => 1,
                    'countryen' => 'GERMANY',
                    'position' => 1,
                    'notice' => '',
                    'taxfree' => 0,
                    'taxfree_ustid' => 0,
                    'taxfree_ustid_checked' => 0,
                    'active' => 1,
                    'iso3' => 'DEU',
                    'display_state_in_registration' => 0,
                    'force_state_in_registration' => 0,
                    'allow_shipping' => 1,
                    'countryarea' => 'deutschland',
                ],
            'stateShipping' => [
                    'id' => 3,
                    'countryID' => 2,
                    'name' => 'Nordrhein-Westfalen',
                    'shortcode' => 'NW',
                    'position' => 0,
                    'active' => 1,
                    'statename' => 'Nordrhein-Westfalen',
                ],
            'payment' => [
                    'id' => 7,
                    'name' => 'SwagPaymentPayPalUnified',
                    'description' => 'PayPal',
                    'template' => '',
                    'class' => '',
                    'table' => '',
                    'hide' => 0,
                    'additionaldescription' => '

    Logo \'PayPal empfohlen\'




Bezahlung per PayPal - einfach, schnell und sicher.',
                    'debit_percent' => 0.0,
                    'surcharge' => 0.0,
                    'surchargestring' => '',
                    'position' => -100,
                    'active' => 1,
                    'esdactive' => 0,
                    'embediframe' => '',
                    'hideprospect' => 0,
                    'action' => 'PaypalUnifiedV2',
                    'pluginID' => 59,
                    'source' => null,
                    'mobile_inactive' => 0,
                    'attributes' => [
                        ],
                    'validation' => [
                        ],
                ],
            'charge_vat' => true,
            'show_net' => false,
        ],
    'shippingaddress' => [
            'id' => 4,
            'company' => 'B2B',
            'department' => 'Einkauf',
            'salutation' => 'mr',
            'firstname' => 'Händler',
            'title' => null,
            'lastname' => 'Kundengruppe-Netto',
            'street' => 'Musterweg 1',
            'zipcode' => '00000',
            'city' => 'Musterstadt',
            'phone' => null,
            'vatId' => null,
            'additionalAddressLine1' => null,
            'additionalAddressLine2' => null,
            'countryId' => 2,
            'stateId' => 3,
            'customer' => [
                    'id' => 2,
                ],
            'country' => [
                    'id' => 2,
                ],
            'state' => [
                    'id' => 3,
                ],
            'userID' => 2,
            'countryID' => 2,
            'stateID' => 3,
            'ustid' => null,
            'additional_address_line1' => null,
            'additional_address_line2' => null,
            'attributes' => [
                ],
        ],
];
