<?php
/**
 * (c) shopware AG <info@shopware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'content' => [
        0 => [
            'id' => 954,
            'sessionID' => '72a648e01e92d85493e25e6d36c20cf4',
            'userID' => 2,
            'articlename' => 'Strandtuch "Ibiza"',
            'articleID' => 178,
            'ordernumber' => 'SW10178',
            'shippingfree' => 0,
            'quantity' => 1,
            'price' => '84,03',
            'netprice' => 84.030000000000001,
            'tax_rate' => 19.0,
            'datum' => '2022-05-18 14:24:33',
            'modus' => 0,
            'esdarticle' => 0,
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36',
            'config' => '',
            'currencyFactor' => 1.0,
            'packunit' => 'Stück',
            'mainDetailId' => 407,
            'articleDetailId' => 407,
            'minpurchase' => 1,
            'taxID' => 1,
            'instock' => 32,
            'suppliernumber' => '',
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'laststock' => 0,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => '',
            'stockmin' => 0,
            'ob_attr1' => '',
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            '__s_order_basket_attributes_id' => 94,
            '__s_order_basket_attributes_basketID' => 954,
            '__s_order_basket_attributes_attribute1' => '',
            '__s_order_basket_attributes_attribute2' => null,
            '__s_order_basket_attributes_attribute3' => null,
            '__s_order_basket_attributes_attribute4' => null,
            '__s_order_basket_attributes_attribute5' => null,
            '__s_order_basket_attributes_attribute6' => null,
            'shippinginfo' => true,
            'esd' => 0,
            'additional_details' => [
                'articleID' => 178,
                'articleDetailsID' => 407,
                'ordernumber' => 'SW10178',
                'highlight' => false,
                'description' => 'paulatim Praecepio lex Edoceo sis conticinium Furtum Heidelberg casula Toto pes an jugiter pe.',
                'description_long' => '
o decertatio. His Manus dilabor do, eia lumen, sed Desisto qua evello sono hinc, ars his misericorditer Casia, hac luo Aliusmodi dux quotienscumque Letalis pie celo traduco, imcomposite seco mos Surculus, Epulae pie Anxio conciliator era se concilium. Terra quam dicto erro prolecto, quo per incommoditas paulatim Praecepio lex Edoceo sis conticinium Furtum Heidelberg casula Toto pes an jugiter pe.

',
                'esd' => false,
                'articleName' => 'Strandtuch "Ibiza"',
                'taxID' => 1,
                'tax' => 19.0,
                'instock' => 32,
                'isAvailable' => true,
                'hasAvailableVariant' => true,
                'weight' => 0.0,
                'shippingtime' => null,
                'pricegroupActive' => false,
                'pricegroupID' => null,
                'length' => 0.0,
                'height' => 0.0,
                'width' => 0.0,
                'laststock' => false,
                'additionaltext' => '',
                'datum' => '2012-08-21',
                'update' => '2022-05-18',
                'sales' => 51,
                'filtergroupID' => null,
                'priceStartingFrom' => null,
                'pseudopricePercent' => null,
                'sVariantArticle' => null,
                'sConfigurator' => false,
                'metaTitle' => '',
                'shippingfree' => false,
                'suppliernumber' => '',
                'notification' => false,
                'ean' => '',
                'keywords' => '',
                'sReleasedate' => '',
                'template' => '',
                'attributes' => [
                    'core' => [
                        'storage' => [
                            'id' => 429,
                            'articledetailsID' => 407,
                            'attr1' => '',
                            'attr2' => '',
                            'attr3' => '',
                            'attr4' => '',
                            'attr5' => '',
                            'attr6' => '',
                            'attr7' => '',
                            'attr8' => '',
                            'attr9' => '',
                            'attr10' => '',
                            'attr11' => '',
                            'attr12' => '',
                            'attr13' => '',
                            'attr14' => '',
                            'attr15' => '',
                            'attr16' => '',
                            'attr17' => null,
                            'attr18' => '',
                            'attr19' => '',
                            'attr20' => '',
                        ],
                    ],
                    'marketing' => [
                        'storage' => [
                        ],
                        'isNew' => false,
                        'isTopSeller' => true,
                        'comingSoon' => false,
                    ],
                ],
                'allowBuyInListing' => true,
                'attr1' => '',
                'attr2' => '',
                'attr3' => '',
                'attr4' => '',
                'attr5' => '',
                'attr6' => '',
                'attr7' => '',
                'attr8' => '',
                'attr9' => '',
                'attr10' => '',
                'attr11' => '',
                'attr12' => '',
                'attr13' => '',
                'attr14' => '',
                'attr15' => '',
                'attr16' => '',
                'attr17' => null,
                'attr18' => '',
                'attr19' => '',
                'attr20' => '',
                'supplierName' => 'Beachdreams Clothes',
                'supplierImg' => 'http://shopware.localhost/media/image/a1/f7/82/beachdreams.png',
                'supplierID' => 12,
                'supplierDescription' => '',
                'supplierMedia' => [
                    'id' => 666,
                    'position' => null,
                    'source' => 'http://shopware.localhost/media/image/a1/f7/82/beachdreams.png',
                    'description' => 'beachdreams',
                    'extension' => 'png',
                    'main' => null,
                    'parentId' => null,
                    'width' => 204,
                    'height' => 85,
                    'thumbnails' => [
                        0 => [
                            'source' => 'http://shopware.localhost/media/image/95/da/c8/beachdreams_200x200.png',
                            'retinaSource' => 'http://shopware.localhost/media/image/83/c0/5c/beachdreams_200x200@2x.png',
                            'sourceSet' => 'http://shopware.localhost/media/image/95/da/c8/beachdreams_200x200.png, http://shopware.localhost/media/image/83/c0/5c/beachdreams_200x200@2x.png 2x',
                            'maxWidth' => '200',
                            'maxHeight' => '200',
                            'attributes' => [
                            ],
                        ],
                        1 => [
                            'source' => 'http://shopware.localhost/media/image/60/3d/67/beachdreams_600x600.png',
                            'retinaSource' => 'http://shopware.localhost/media/image/9b/c0/49/beachdreams_600x600@2x.png',
                            'sourceSet' => 'http://shopware.localhost/media/image/60/3d/67/beachdreams_600x600.png, http://shopware.localhost/media/image/9b/c0/49/beachdreams_600x600@2x.png 2x',
                            'maxWidth' => '600',
                            'maxHeight' => '600',
                            'attributes' => [
                            ],
                        ],
                        2 => [
                            'source' => 'http://shopware.localhost/media/image/3f/32/20/beachdreams_1280x1280.png',
                            'retinaSource' => 'http://shopware.localhost/media/image/b9/3b/25/beachdreams_1280x1280@2x.png',
                            'sourceSet' => 'http://shopware.localhost/media/image/3f/32/20/beachdreams_1280x1280.png, http://shopware.localhost/media/image/b9/3b/25/beachdreams_1280x1280@2x.png 2x',
                            'maxWidth' => '1280',
                            'maxHeight' => '1280',
                            'attributes' => [
                            ],
                        ],
                    ],
                    'attributes' => [
                    ],
                    'attribute' => [
                    ],
                ],
                'supplier_attributes' => [
                ],
                'newArticle' => false,
                'sUpcoming' => false,
                'topseller' => true,
                'valFrom' => 1,
                'valTo' => null,
                'from' => 1,
                'to' => null,
                'price' => '84,03',
                'pseudoprice' => '0',
                'referenceprice' => '0',
                'has_pseudoprice' => false,
                'price_numeric' => 84.030000000000001,
                'pseudoprice_numeric' => 0.0,
                'price_attributes' => [
                ],
                'pricegroup' => 'EK',
                'regulationPrice' => null,
                'minpurchase' => 1,
                'maxpurchase' => '100',
                'purchasesteps' => 1,
                'purchaseunit' => null,
                'referenceunit' => null,
                'packunit' => 'Stück',
                'unitID' => null,
                'sUnit' => [
                    'unit' => null,
                    'description' => null,
                ],
                'unit_attributes' => [
                ],
                'image' => [
                    'id' => 445,
                    'position' => null,
                    'source' => 'http://shopware.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                    'description' => '',
                    'extension' => 'jpg',
                    'main' => true,
                    'parentId' => null,
                    'width' => 1698,
                    'height' => 1131,
                    'thumbnails' => [
                        0 => [
                            'source' => 'http://shopware.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                            'retinaSource' => 'http://shopware.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                            'sourceSet' => 'http://shopware.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg, http://shopware.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg 2x',
                            'maxWidth' => '200',
                            'maxHeight' => '200',
                            'attributes' => [
                            ],
                        ],
                        1 => [
                            'source' => 'http://shopware.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                            'retinaSource' => 'http://shopware.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                            'sourceSet' => 'http://shopware.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg, http://shopware.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg 2x',
                            'maxWidth' => '600',
                            'maxHeight' => '600',
                            'attributes' => [
                            ],
                        ],
                        2 => [
                            'source' => 'http://shopware.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                            'retinaSource' => 'http://shopware.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                            'sourceSet' => 'http://shopware.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg, http://shopware.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg 2x',
                            'maxWidth' => '1280',
                            'maxHeight' => '1280',
                            'attributes' => [
                            ],
                        ],
                    ],
                    'attributes' => [
                    ],
                    'attribute' => [
                    ],
                ],
                'prices' => [
                    0 => [
                        'valFrom' => 1,
                        'valTo' => null,
                        'from' => 1,
                        'to' => null,
                        'price' => '84,03',
                        'pseudoprice' => '0',
                        'referenceprice' => '0',
                        'pseudopricePercent' => null,
                        'has_pseudoprice' => false,
                        'price_numeric' => 84.030000000000001,
                        'pseudoprice_numeric' => 0.0,
                        'price_attributes' => [
                        ],
                        'pricegroup' => 'EK',
                        'regulationPrice' => null,
                        'minpurchase' => 1,
                        'maxpurchase' => '100',
                        'purchasesteps' => 1,
                        'purchaseunit' => null,
                        'referenceunit' => null,
                        'packunit' => 'Stück',
                        'unitID' => null,
                        'sUnit' => [
                            'unit' => null,
                            'description' => null,
                        ],
                        'unit_attributes' => [
                        ],
                    ],
                ],
                'linkBasket' => 'shopware.php?sViewport=basket&sAdd=SW10178',
                'linkDetails' => 'shopware.php?sViewport=detail&sArticle=178',
                'linkVariant' => 'shopware.php?sViewport=detail&sArticle=178&number=SW10178',
            ],
            'amountWithTax' => 100.0,
            'amount' => '84,03',
            'amountnet' => '84,03',
            'priceNumeric' => 84.030000000000001,
            'amountNumeric' => 84.030000000000001,
            'amountnetNumeric' => 84.030000000000001,
            'image' => [
                'id' => 445,
                'position' => null,
                'source' => 'http://shopware.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                'description' => '',
                'extension' => 'jpg',
                'main' => true,
                'parentId' => null,
                'width' => 1698,
                'height' => 1131,
                'thumbnails' => [
                    0 => [
                        'source' => 'http://shopware.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                        'retinaSource' => 'http://shopware.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                        'sourceSet' => 'http://shopware.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg, http://shopware.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg 2x',
                        'maxWidth' => '200',
                        'maxHeight' => '200',
                        'attributes' => [
                        ],
                    ],
                    1 => [
                        'source' => 'http://shopware.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                        'retinaSource' => 'http://shopware.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                        'sourceSet' => 'http://shopware.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg, http://shopware.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg 2x',
                        'maxWidth' => '600',
                        'maxHeight' => '600',
                        'attributes' => [
                        ],
                    ],
                    2 => [
                        'source' => 'http://shopware.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                        'retinaSource' => 'http://shopware.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                        'sourceSet' => 'http://shopware.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg, http://shopware.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg 2x',
                        'maxWidth' => '1280',
                        'maxHeight' => '1280',
                        'attributes' => [
                        ],
                    ],
                ],
                'attributes' => [
                ],
                'attribute' => [
                ],
                'src' => [
                    'original' => 'http://shopware.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                    0 => 'http://shopware.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                    1 => 'http://shopware.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                    2 => 'http://shopware.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                ],
                'srchd' => [
                    'original' => 'http://shopware.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                    0 => 'http://shopware.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                    1 => 'http://shopware.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                    2 => 'http://shopware.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 1131,
                        'height' => 1698,
                    ],
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=178',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=954',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW10178',
            'tax' => '15,97',
        ],
        1 => [
            'id' => 955,
            'sessionID' => '72a648e01e92d85493e25e6d36c20cf4',
            'userID' => 2,
            'articlename' => 'Strandtuch in mehreren Farben blau',
            'articleID' => 179,
            'ordernumber' => 'SW10179.1',
            'shippingfree' => 0,
            'quantity' => 1,
            'price' => '84,03',
            'netprice' => 84.030000000000001,
            'tax_rate' => 19.0,
            'datum' => '2022-05-18 14:24:56',
            'modus' => 0,
            'esdarticle' => 0,
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36',
            'config' => '',
            'currencyFactor' => 1.0,
            'packunit' => '',
            'mainDetailId' => 409,
            'articleDetailId' => 409,
            'minpurchase' => 1,
            'taxID' => 1,
            'instock' => 91,
            'suppliernumber' => '',
            'maxpurchase' => 91,
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'laststock' => 1,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => '',
            'stockmin' => 0,
            'ob_attr1' => '',
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            '__s_order_basket_attributes_id' => 95,
            '__s_order_basket_attributes_basketID' => 955,
            '__s_order_basket_attributes_attribute1' => '',
            '__s_order_basket_attributes_attribute2' => null,
            '__s_order_basket_attributes_attribute3' => null,
            '__s_order_basket_attributes_attribute4' => null,
            '__s_order_basket_attributes_attribute5' => null,
            '__s_order_basket_attributes_attribute6' => null,
            'shippinginfo' => true,
            'esd' => 0,
            'additional_details' => [
                'articleID' => 179,
                'articleDetailsID' => 409,
                'ordernumber' => 'SW10179.1',
                'highlight' => true,
                'description' => 'Pulpa impenetrabiilis. His reus divum illum quisque ut Redeo. Ubi cui nam ira supplicium Ut Exporrigo, per algeo aute.',
                'description_long' => '
Eficio uterus vel fugo pes eo ops altor. Me consulo sui voveo ymo Ficus Libero nex modo sui velitatio opportunus, qui cum res termino unde potestas Palmula do donum Chalybs se illius. Pars ars eo labes upilio. Se quin etsi Lac se at, do. Hi per ora lentulus Concino, en, vox se mei Pulpa impenetrabiilis. His reus divum illum quisque ut Redeo. Ubi cui nam ira supplicium Ut Exporrigo, per algeo aute.

',
                'esd' => false,
                'articleName' => 'Strandtuch in mehreren Farben',
                'taxID' => 1,
                'tax' => 19.0,
                'instock' => 91,
                'isAvailable' => true,
                'hasAvailableVariant' => true,
                'weight' => 0.0,
                'shippingtime' => null,
                'pricegroupActive' => false,
                'pricegroupID' => null,
                'length' => 0.0,
                'height' => 0.0,
                'width' => 0.0,
                'laststock' => true,
                'additionaltext' => 'blau',
                'datum' => '2012-08-21',
                'update' => '2022-05-18',
                'sales' => 0,
                'filtergroupID' => null,
                'priceStartingFrom' => '37,81',
                'pseudopricePercent' => null,
                'sVariantArticle' => null,
                'sConfigurator' => true,
                'metaTitle' => '',
                'shippingfree' => false,
                'suppliernumber' => '',
                'notification' => false,
                'ean' => '',
                'keywords' => '',
                'sReleasedate' => '',
                'template' => '',
                'attributes' => [
                    'core' => [
                        'storage' => [
                            'id' => 431,
                            'articledetailsID' => 409,
                            'attr1' => '',
                            'attr2' => '',
                            'attr3' => '',
                            'attr4' => '',
                            'attr5' => '',
                            'attr6' => '',
                            'attr7' => '',
                            'attr8' => '',
                            'attr9' => '',
                            'attr10' => '',
                            'attr11' => '',
                            'attr12' => '',
                            'attr13' => '',
                            'attr14' => '',
                            'attr15' => '',
                            'attr16' => '',
                            'attr17' => null,
                            'attr18' => '',
                            'attr19' => '',
                            'attr20' => '',
                        ],
                    ],
                    'marketing' => [
                        'storage' => [
                        ],
                        'isNew' => false,
                        'isTopSeller' => false,
                        'comingSoon' => false,
                    ],
                ],
                'allowBuyInListing' => false,
                'attr1' => '',
                'attr2' => '',
                'attr3' => '',
                'attr4' => '',
                'attr5' => '',
                'attr6' => '',
                'attr7' => '',
                'attr8' => '',
                'attr9' => '',
                'attr10' => '',
                'attr11' => '',
                'attr12' => '',
                'attr13' => '',
                'attr14' => '',
                'attr15' => '',
                'attr16' => '',
                'attr17' => null,
                'attr18' => '',
                'attr19' => '',
                'attr20' => '',
                'supplierName' => 'Beachdreams Clothes',
                'supplierImg' => 'http://shopware.localhost/media/image/a1/f7/82/beachdreams.png',
                'supplierID' => 12,
                'supplierDescription' => '',
                'supplierMedia' => [
                    'id' => 666,
                    'position' => null,
                    'source' => 'http://shopware.localhost/media/image/a1/f7/82/beachdreams.png',
                    'description' => 'beachdreams',
                    'extension' => 'png',
                    'main' => null,
                    'parentId' => null,
                    'width' => 204,
                    'height' => 85,
                    'thumbnails' => [
                        0 => [
                            'source' => 'http://shopware.localhost/media/image/95/da/c8/beachdreams_200x200.png',
                            'retinaSource' => 'http://shopware.localhost/media/image/83/c0/5c/beachdreams_200x200@2x.png',
                            'sourceSet' => 'http://shopware.localhost/media/image/95/da/c8/beachdreams_200x200.png, http://shopware.localhost/media/image/83/c0/5c/beachdreams_200x200@2x.png 2x',
                            'maxWidth' => '200',
                            'maxHeight' => '200',
                            'attributes' => [
                            ],
                        ],
                        1 => [
                            'source' => 'http://shopware.localhost/media/image/60/3d/67/beachdreams_600x600.png',
                            'retinaSource' => 'http://shopware.localhost/media/image/9b/c0/49/beachdreams_600x600@2x.png',
                            'sourceSet' => 'http://shopware.localhost/media/image/60/3d/67/beachdreams_600x600.png, http://shopware.localhost/media/image/9b/c0/49/beachdreams_600x600@2x.png 2x',
                            'maxWidth' => '600',
                            'maxHeight' => '600',
                            'attributes' => [
                            ],
                        ],
                        2 => [
                            'source' => 'http://shopware.localhost/media/image/3f/32/20/beachdreams_1280x1280.png',
                            'retinaSource' => 'http://shopware.localhost/media/image/b9/3b/25/beachdreams_1280x1280@2x.png',
                            'sourceSet' => 'http://shopware.localhost/media/image/3f/32/20/beachdreams_1280x1280.png, http://shopware.localhost/media/image/b9/3b/25/beachdreams_1280x1280@2x.png 2x',
                            'maxWidth' => '1280',
                            'maxHeight' => '1280',
                            'attributes' => [
                            ],
                        ],
                    ],
                    'attributes' => [
                    ],
                    'attribute' => [
                    ],
                ],
                'supplier_attributes' => [
                ],
                'newArticle' => false,
                'sUpcoming' => false,
                'topseller' => false,
                'valFrom' => 1,
                'valTo' => null,
                'from' => 1,
                'to' => null,
                'price' => '37,81',
                'pseudoprice' => '0',
                'referenceprice' => null,
                'has_pseudoprice' => false,
                'price_numeric' => 37.810000000000002,
                'pseudoprice_numeric' => 0.0,
                'price_attributes' => [
                ],
                'pricegroup' => 'EK',
                'regulationPrice' => null,
                'minpurchase' => 1,
                'maxpurchase' => '100',
                'purchasesteps' => 1,
                'purchaseunit' => null,
                'referenceunit' => null,
                'packunit' => '',
                'unitID' => null,
                'sUnit' => [
                    'unit' => null,
                    'description' => null,
                ],
                'unit_attributes' => [
                ],
                'image' => [
                    'id' => 446,
                    'position' => null,
                    'source' => 'http://shopware.localhost/media/image/60/6c/22/Strandtuch-mehrfarbig.jpg',
                    'description' => '',
                    'extension' => 'jpg',
                    'main' => true,
                    'parentId' => null,
                    'width' => 849,
                    'height' => 565,
                    'thumbnails' => [
                        0 => [
                            'source' => 'http://shopware.localhost/media/image/df/77/e2/Strandtuch-mehrfarbig_200x200.jpg',
                            'retinaSource' => 'http://shopware.localhost/media/image/41/bb/26/Strandtuch-mehrfarbig_200x200@2x.jpg',
                            'sourceSet' => 'http://shopware.localhost/media/image/df/77/e2/Strandtuch-mehrfarbig_200x200.jpg, http://shopware.localhost/media/image/41/bb/26/Strandtuch-mehrfarbig_200x200@2x.jpg 2x',
                            'maxWidth' => '200',
                            'maxHeight' => '200',
                            'attributes' => [
                            ],
                        ],
                        1 => [
                            'source' => 'http://shopware.localhost/media/image/51/80/75/Strandtuch-mehrfarbig_600x600.jpg',
                            'retinaSource' => 'http://shopware.localhost/media/image/a4/30/53/Strandtuch-mehrfarbig_600x600@2x.jpg',
                            'sourceSet' => 'http://shopware.localhost/media/image/51/80/75/Strandtuch-mehrfarbig_600x600.jpg, http://shopware.localhost/media/image/a4/30/53/Strandtuch-mehrfarbig_600x600@2x.jpg 2x',
                            'maxWidth' => '600',
                            'maxHeight' => '600',
                            'attributes' => [
                            ],
                        ],
                        2 => [
                            'source' => 'http://shopware.localhost/media/image/9b/04/f3/Strandtuch-mehrfarbig_1280x1280.jpg',
                            'retinaSource' => 'http://shopware.localhost/media/image/43/72/fb/Strandtuch-mehrfarbig_1280x1280@2x.jpg',
                            'sourceSet' => 'http://shopware.localhost/media/image/9b/04/f3/Strandtuch-mehrfarbig_1280x1280.jpg, http://shopware.localhost/media/image/43/72/fb/Strandtuch-mehrfarbig_1280x1280@2x.jpg 2x',
                            'maxWidth' => '1280',
                            'maxHeight' => '1280',
                            'attributes' => [
                            ],
                        ],
                    ],
                    'attributes' => [
                    ],
                    'attribute' => [
                    ],
                ],
                'prices' => [
                    0 => [
                        'valFrom' => 1,
                        'valTo' => null,
                        'from' => 1,
                        'to' => null,
                        'price' => '84,03',
                        'pseudoprice' => '0',
                        'referenceprice' => '0',
                        'pseudopricePercent' => null,
                        'has_pseudoprice' => false,
                        'price_numeric' => 84.030000000000001,
                        'pseudoprice_numeric' => 0.0,
                        'price_attributes' => [
                        ],
                        'pricegroup' => 'EK',
                        'regulationPrice' => null,
                        'minpurchase' => 1,
                        'maxpurchase' => '100',
                        'purchasesteps' => 1,
                        'purchaseunit' => null,
                        'referenceunit' => null,
                        'packunit' => '',
                        'unitID' => null,
                        'sUnit' => [
                            'unit' => null,
                            'description' => null,
                        ],
                        'unit_attributes' => [
                        ],
                    ],
                ],
                'linkBasket' => 'shopware.php?sViewport=basket&sAdd=SW10179.1',
                'linkDetails' => 'shopware.php?sViewport=detail&sArticle=179',
                'linkVariant' => 'shopware.php?sViewport=detail&sArticle=179&number=SW10179.1',
            ],
            'amountWithTax' => 100.0,
            'amount' => '84,03',
            'amountnet' => '84,03',
            'priceNumeric' => 84.030000000000001,
            'amountNumeric' => 84.030000000000001,
            'amountnetNumeric' => 84.030000000000001,
            'image' => [
                'id' => 446,
                'position' => null,
                'source' => 'http://shopware.localhost/media/image/60/6c/22/Strandtuch-mehrfarbig.jpg',
                'description' => '',
                'extension' => 'jpg',
                'main' => true,
                'parentId' => null,
                'width' => 849,
                'height' => 565,
                'thumbnails' => [
                    0 => [
                        'source' => 'http://shopware.localhost/media/image/df/77/e2/Strandtuch-mehrfarbig_200x200.jpg',
                        'retinaSource' => 'http://shopware.localhost/media/image/41/bb/26/Strandtuch-mehrfarbig_200x200@2x.jpg',
                        'sourceSet' => 'http://shopware.localhost/media/image/df/77/e2/Strandtuch-mehrfarbig_200x200.jpg, http://shopware.localhost/media/image/41/bb/26/Strandtuch-mehrfarbig_200x200@2x.jpg 2x',
                        'maxWidth' => '200',
                        'maxHeight' => '200',
                        'attributes' => [
                        ],
                    ],
                    1 => [
                        'source' => 'http://shopware.localhost/media/image/51/80/75/Strandtuch-mehrfarbig_600x600.jpg',
                        'retinaSource' => 'http://shopware.localhost/media/image/a4/30/53/Strandtuch-mehrfarbig_600x600@2x.jpg',
                        'sourceSet' => 'http://shopware.localhost/media/image/51/80/75/Strandtuch-mehrfarbig_600x600.jpg, http://shopware.localhost/media/image/a4/30/53/Strandtuch-mehrfarbig_600x600@2x.jpg 2x',
                        'maxWidth' => '600',
                        'maxHeight' => '600',
                        'attributes' => [
                        ],
                    ],
                    2 => [
                        'source' => 'http://shopware.localhost/media/image/9b/04/f3/Strandtuch-mehrfarbig_1280x1280.jpg',
                        'retinaSource' => 'http://shopware.localhost/media/image/43/72/fb/Strandtuch-mehrfarbig_1280x1280@2x.jpg',
                        'sourceSet' => 'http://shopware.localhost/media/image/9b/04/f3/Strandtuch-mehrfarbig_1280x1280.jpg, http://shopware.localhost/media/image/43/72/fb/Strandtuch-mehrfarbig_1280x1280@2x.jpg 2x',
                        'maxWidth' => '1280',
                        'maxHeight' => '1280',
                        'attributes' => [
                        ],
                    ],
                ],
                'attributes' => [
                ],
                'attribute' => [
                ],
                'src' => [
                    'original' => 'http://shopware.localhost/media/image/60/6c/22/Strandtuch-mehrfarbig.jpg',
                    0 => 'http://shopware.localhost/media/image/df/77/e2/Strandtuch-mehrfarbig_200x200.jpg',
                    1 => 'http://shopware.localhost/media/image/51/80/75/Strandtuch-mehrfarbig_600x600.jpg',
                    2 => 'http://shopware.localhost/media/image/9b/04/f3/Strandtuch-mehrfarbig_1280x1280.jpg',
                ],
                'srchd' => [
                    'original' => 'http://shopware.localhost/media/image/60/6c/22/Strandtuch-mehrfarbig.jpg',
                    0 => 'http://shopware.localhost/media/image/41/bb/26/Strandtuch-mehrfarbig_200x200@2x.jpg',
                    1 => 'http://shopware.localhost/media/image/a4/30/53/Strandtuch-mehrfarbig_600x600@2x.jpg',
                    2 => 'http://shopware.localhost/media/image/43/72/fb/Strandtuch-mehrfarbig_1280x1280@2x.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 565,
                        'height' => 849,
                    ],
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=179',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=955',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW10179.1',
            'tax' => '15,97',
        ],
        2 => [
            'id' => 956,
            'sessionID' => '72a648e01e92d85493e25e6d36c20cf4',
            'userID' => 2,
            'articlename' => 'Strandtuch in mehreren Farben grün',
            'articleID' => 179,
            'ordernumber' => 'SW10179.3',
            'shippingfree' => 0,
            'quantity' => 1,
            'price' => '84,03',
            'netprice' => 84.030000000000001,
            'tax_rate' => 19.0,
            'datum' => '2022-05-18 14:25:06',
            'modus' => 0,
            'esdarticle' => 0,
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36',
            'config' => '',
            'currencyFactor' => 1.0,
            'packunit' => '',
            'mainDetailId' => 409,
            'articleDetailId' => 411,
            'minpurchase' => 1,
            'taxID' => 1,
            'instock' => 91,
            'suppliernumber' => '',
            'maxpurchase' => 91,
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'laststock' => 1,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => '',
            'stockmin' => 0,
            'ob_attr1' => '',
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            '__s_order_basket_attributes_id' => 96,
            '__s_order_basket_attributes_basketID' => 956,
            '__s_order_basket_attributes_attribute1' => '',
            '__s_order_basket_attributes_attribute2' => null,
            '__s_order_basket_attributes_attribute3' => null,
            '__s_order_basket_attributes_attribute4' => null,
            '__s_order_basket_attributes_attribute5' => null,
            '__s_order_basket_attributes_attribute6' => null,
            'shippinginfo' => true,
            'esd' => 0,
            'additional_details' => [
                'articleID' => 179,
                'articleDetailsID' => 411,
                'ordernumber' => 'SW10179.3',
                'highlight' => true,
                'description' => 'Pulpa impenetrabiilis. His reus divum illum quisque ut Redeo. Ubi cui nam ira supplicium Ut Exporrigo, per algeo aute.',
                'description_long' => '
Eficio uterus vel fugo pes eo ops altor. Me consulo sui voveo ymo Ficus Libero nex modo sui velitatio opportunus, qui cum res termino unde potestas Palmula do donum Chalybs se illius. Pars ars eo labes upilio. Se quin etsi Lac se at, do. Hi per ora lentulus Concino, en, vox se mei Pulpa impenetrabiilis. His reus divum illum quisque ut Redeo. Ubi cui nam ira supplicium Ut Exporrigo, per algeo aute.

',
                'esd' => false,
                'articleName' => 'Strandtuch in mehreren Farben',
                'taxID' => 1,
                'tax' => 19.0,
                'instock' => 91,
                'isAvailable' => true,
                'hasAvailableVariant' => true,
                'weight' => 0.0,
                'shippingtime' => null,
                'pricegroupActive' => false,
                'pricegroupID' => null,
                'length' => 0.0,
                'height' => 0.0,
                'width' => 0.0,
                'laststock' => true,
                'additionaltext' => 'grün',
                'datum' => '2012-08-21',
                'update' => '2022-05-18',
                'sales' => 0,
                'filtergroupID' => null,
                'priceStartingFrom' => '37,81',
                'pseudopricePercent' => null,
                'sVariantArticle' => null,
                'sConfigurator' => true,
                'metaTitle' => '',
                'shippingfree' => false,
                'suppliernumber' => '',
                'notification' => false,
                'ean' => '',
                'keywords' => '',
                'sReleasedate' => '',
                'template' => '',
                'attributes' => [
                    'core' => [
                        'storage' => [
                            'id' => 433,
                            'articledetailsID' => 411,
                            'attr1' => '',
                            'attr2' => '',
                            'attr3' => '',
                            'attr4' => '',
                            'attr5' => '',
                            'attr6' => '',
                            'attr7' => '',
                            'attr8' => '',
                            'attr9' => '',
                            'attr10' => '',
                            'attr11' => '',
                            'attr12' => '',
                            'attr13' => '',
                            'attr14' => '',
                            'attr15' => '',
                            'attr16' => '',
                            'attr17' => null,
                            'attr18' => '',
                            'attr19' => '',
                            'attr20' => '',
                        ],
                    ],
                    'marketing' => [
                        'storage' => [
                        ],
                        'isNew' => false,
                        'isTopSeller' => false,
                        'comingSoon' => false,
                    ],
                ],
                'allowBuyInListing' => false,
                'attr1' => '',
                'attr2' => '',
                'attr3' => '',
                'attr4' => '',
                'attr5' => '',
                'attr6' => '',
                'attr7' => '',
                'attr8' => '',
                'attr9' => '',
                'attr10' => '',
                'attr11' => '',
                'attr12' => '',
                'attr13' => '',
                'attr14' => '',
                'attr15' => '',
                'attr16' => '',
                'attr17' => null,
                'attr18' => '',
                'attr19' => '',
                'attr20' => '',
                'supplierName' => 'Beachdreams Clothes',
                'supplierImg' => 'http://shopware.localhost/media/image/a1/f7/82/beachdreams.png',
                'supplierID' => 12,
                'supplierDescription' => '',
                'supplierMedia' => [
                    'id' => 666,
                    'position' => null,
                    'source' => 'http://shopware.localhost/media/image/a1/f7/82/beachdreams.png',
                    'description' => 'beachdreams',
                    'extension' => 'png',
                    'main' => null,
                    'parentId' => null,
                    'width' => 204,
                    'height' => 85,
                    'thumbnails' => [
                        0 => [
                            'source' => 'http://shopware.localhost/media/image/95/da/c8/beachdreams_200x200.png',
                            'retinaSource' => 'http://shopware.localhost/media/image/83/c0/5c/beachdreams_200x200@2x.png',
                            'sourceSet' => 'http://shopware.localhost/media/image/95/da/c8/beachdreams_200x200.png, http://shopware.localhost/media/image/83/c0/5c/beachdreams_200x200@2x.png 2x',
                            'maxWidth' => '200',
                            'maxHeight' => '200',
                            'attributes' => [
                            ],
                        ],
                        1 => [
                            'source' => 'http://shopware.localhost/media/image/60/3d/67/beachdreams_600x600.png',
                            'retinaSource' => 'http://shopware.localhost/media/image/9b/c0/49/beachdreams_600x600@2x.png',
                            'sourceSet' => 'http://shopware.localhost/media/image/60/3d/67/beachdreams_600x600.png, http://shopware.localhost/media/image/9b/c0/49/beachdreams_600x600@2x.png 2x',
                            'maxWidth' => '600',
                            'maxHeight' => '600',
                            'attributes' => [
                            ],
                        ],
                        2 => [
                            'source' => 'http://shopware.localhost/media/image/3f/32/20/beachdreams_1280x1280.png',
                            'retinaSource' => 'http://shopware.localhost/media/image/b9/3b/25/beachdreams_1280x1280@2x.png',
                            'sourceSet' => 'http://shopware.localhost/media/image/3f/32/20/beachdreams_1280x1280.png, http://shopware.localhost/media/image/b9/3b/25/beachdreams_1280x1280@2x.png 2x',
                            'maxWidth' => '1280',
                            'maxHeight' => '1280',
                            'attributes' => [
                            ],
                        ],
                    ],
                    'attributes' => [
                    ],
                    'attribute' => [
                    ],
                ],
                'supplier_attributes' => [
                ],
                'newArticle' => false,
                'sUpcoming' => false,
                'topseller' => false,
                'valFrom' => 1,
                'valTo' => null,
                'from' => 1,
                'to' => null,
                'price' => '37,81',
                'pseudoprice' => '0',
                'referenceprice' => null,
                'has_pseudoprice' => false,
                'price_numeric' => 37.810000000000002,
                'pseudoprice_numeric' => 0.0,
                'price_attributes' => [
                ],
                'pricegroup' => 'EK',
                'regulationPrice' => null,
                'minpurchase' => 1,
                'maxpurchase' => '100',
                'purchasesteps' => 1,
                'purchaseunit' => null,
                'referenceunit' => null,
                'packunit' => '',
                'unitID' => null,
                'sUnit' => [
                    'unit' => null,
                    'description' => null,
                ],
                'unit_attributes' => [
                ],
                'image' => [
                    'id' => 446,
                    'position' => null,
                    'source' => 'http://shopware.localhost/media/image/60/6c/22/Strandtuch-mehrfarbig.jpg',
                    'description' => '',
                    'extension' => 'jpg',
                    'main' => true,
                    'parentId' => null,
                    'width' => 849,
                    'height' => 565,
                    'thumbnails' => [
                        0 => [
                            'source' => 'http://shopware.localhost/media/image/df/77/e2/Strandtuch-mehrfarbig_200x200.jpg',
                            'retinaSource' => 'http://shopware.localhost/media/image/41/bb/26/Strandtuch-mehrfarbig_200x200@2x.jpg',
                            'sourceSet' => 'http://shopware.localhost/media/image/df/77/e2/Strandtuch-mehrfarbig_200x200.jpg, http://shopware.localhost/media/image/41/bb/26/Strandtuch-mehrfarbig_200x200@2x.jpg 2x',
                            'maxWidth' => '200',
                            'maxHeight' => '200',
                            'attributes' => [
                            ],
                        ],
                        1 => [
                            'source' => 'http://shopware.localhost/media/image/51/80/75/Strandtuch-mehrfarbig_600x600.jpg',
                            'retinaSource' => 'http://shopware.localhost/media/image/a4/30/53/Strandtuch-mehrfarbig_600x600@2x.jpg',
                            'sourceSet' => 'http://shopware.localhost/media/image/51/80/75/Strandtuch-mehrfarbig_600x600.jpg, http://shopware.localhost/media/image/a4/30/53/Strandtuch-mehrfarbig_600x600@2x.jpg 2x',
                            'maxWidth' => '600',
                            'maxHeight' => '600',
                            'attributes' => [
                            ],
                        ],
                        2 => [
                            'source' => 'http://shopware.localhost/media/image/9b/04/f3/Strandtuch-mehrfarbig_1280x1280.jpg',
                            'retinaSource' => 'http://shopware.localhost/media/image/43/72/fb/Strandtuch-mehrfarbig_1280x1280@2x.jpg',
                            'sourceSet' => 'http://shopware.localhost/media/image/9b/04/f3/Strandtuch-mehrfarbig_1280x1280.jpg, http://shopware.localhost/media/image/43/72/fb/Strandtuch-mehrfarbig_1280x1280@2x.jpg 2x',
                            'maxWidth' => '1280',
                            'maxHeight' => '1280',
                            'attributes' => [
                            ],
                        ],
                    ],
                    'attributes' => [
                    ],
                    'attribute' => [
                    ],
                ],
                'prices' => [
                    0 => [
                        'valFrom' => 1,
                        'valTo' => null,
                        'from' => 1,
                        'to' => null,
                        'price' => '84,03',
                        'pseudoprice' => '0',
                        'referenceprice' => '0',
                        'pseudopricePercent' => null,
                        'has_pseudoprice' => false,
                        'price_numeric' => 84.030000000000001,
                        'pseudoprice_numeric' => 0.0,
                        'price_attributes' => [
                        ],
                        'pricegroup' => 'EK',
                        'regulationPrice' => null,
                        'minpurchase' => 1,
                        'maxpurchase' => '100',
                        'purchasesteps' => 1,
                        'purchaseunit' => null,
                        'referenceunit' => null,
                        'packunit' => '',
                        'unitID' => null,
                        'sUnit' => [
                            'unit' => null,
                            'description' => null,
                        ],
                        'unit_attributes' => [
                        ],
                    ],
                ],
                'linkBasket' => 'shopware.php?sViewport=basket&sAdd=SW10179.3',
                'linkDetails' => 'shopware.php?sViewport=detail&sArticle=179',
                'linkVariant' => 'shopware.php?sViewport=detail&sArticle=179&number=SW10179.3',
            ],
            'amountWithTax' => 100.0,
            'amount' => '84,03',
            'amountnet' => '84,03',
            'priceNumeric' => 84.030000000000001,
            'amountNumeric' => 84.030000000000001,
            'amountnetNumeric' => 84.030000000000001,
            'image' => [
                'id' => 446,
                'position' => null,
                'source' => 'http://shopware.localhost/media/image/60/6c/22/Strandtuch-mehrfarbig.jpg',
                'description' => '',
                'extension' => 'jpg',
                'main' => true,
                'parentId' => null,
                'width' => 849,
                'height' => 565,
                'thumbnails' => [
                    0 => [
                        'source' => 'http://shopware.localhost/media/image/df/77/e2/Strandtuch-mehrfarbig_200x200.jpg',
                        'retinaSource' => 'http://shopware.localhost/media/image/41/bb/26/Strandtuch-mehrfarbig_200x200@2x.jpg',
                        'sourceSet' => 'http://shopware.localhost/media/image/df/77/e2/Strandtuch-mehrfarbig_200x200.jpg, http://shopware.localhost/media/image/41/bb/26/Strandtuch-mehrfarbig_200x200@2x.jpg 2x',
                        'maxWidth' => '200',
                        'maxHeight' => '200',
                        'attributes' => [
                        ],
                    ],
                    1 => [
                        'source' => 'http://shopware.localhost/media/image/51/80/75/Strandtuch-mehrfarbig_600x600.jpg',
                        'retinaSource' => 'http://shopware.localhost/media/image/a4/30/53/Strandtuch-mehrfarbig_600x600@2x.jpg',
                        'sourceSet' => 'http://shopware.localhost/media/image/51/80/75/Strandtuch-mehrfarbig_600x600.jpg, http://shopware.localhost/media/image/a4/30/53/Strandtuch-mehrfarbig_600x600@2x.jpg 2x',
                        'maxWidth' => '600',
                        'maxHeight' => '600',
                        'attributes' => [
                        ],
                    ],
                    2 => [
                        'source' => 'http://shopware.localhost/media/image/9b/04/f3/Strandtuch-mehrfarbig_1280x1280.jpg',
                        'retinaSource' => 'http://shopware.localhost/media/image/43/72/fb/Strandtuch-mehrfarbig_1280x1280@2x.jpg',
                        'sourceSet' => 'http://shopware.localhost/media/image/9b/04/f3/Strandtuch-mehrfarbig_1280x1280.jpg, http://shopware.localhost/media/image/43/72/fb/Strandtuch-mehrfarbig_1280x1280@2x.jpg 2x',
                        'maxWidth' => '1280',
                        'maxHeight' => '1280',
                        'attributes' => [
                        ],
                    ],
                ],
                'attributes' => [
                ],
                'attribute' => [
                ],
                'src' => [
                    'original' => 'http://shopware.localhost/media/image/60/6c/22/Strandtuch-mehrfarbig.jpg',
                    0 => 'http://shopware.localhost/media/image/df/77/e2/Strandtuch-mehrfarbig_200x200.jpg',
                    1 => 'http://shopware.localhost/media/image/51/80/75/Strandtuch-mehrfarbig_600x600.jpg',
                    2 => 'http://shopware.localhost/media/image/9b/04/f3/Strandtuch-mehrfarbig_1280x1280.jpg',
                ],
                'srchd' => [
                    'original' => 'http://shopware.localhost/media/image/60/6c/22/Strandtuch-mehrfarbig.jpg',
                    0 => 'http://shopware.localhost/media/image/41/bb/26/Strandtuch-mehrfarbig_200x200@2x.jpg',
                    1 => 'http://shopware.localhost/media/image/a4/30/53/Strandtuch-mehrfarbig_600x600@2x.jpg',
                    2 => 'http://shopware.localhost/media/image/43/72/fb/Strandtuch-mehrfarbig_1280x1280@2x.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 565,
                        'height' => 849,
                    ],
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=179',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=956',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW10179.3',
            'tax' => '15,97',
        ],
    ],
    'Amount' => '252,09',
    'AmountNet' => '252,09',
    'Quantity' => 3,
    'AmountNumeric' => 255.99000000000001,
    'AmountNetNumeric' => 255.37,
    'AmountWithTax' => '300,00',
    'AmountWithTaxNumeric' => 303.89999999999998,
    'sCurrencyId' => 1,
    'sCurrencyName' => 'EUR',
    'sCurrencyFactor' => 1.0,
    'sShippingcostsWithTax' => 3.8999999999999999,
    'sShippingcostsNet' => 3.2799999999999998,
    'sShippingcostsTax' => 19.0,
    'sTaxRates' => [
        '19.00' => 48.530000000000001,
    ],
    'sShippingcosts' => 3.2799999999999998,
    'sAmount' => 255.37,
    'sAmountTax' => 48.530000000000001,
    'sAmountWithTax' => 303.89999999999998,
];
