<?php
/**
 * (c) shopware AG <info@shopware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'content' => [
        [
            'id' => '670',
            'sessionID' => '2glivht14j7tl61bp793si4bjg',
            'userID' => '1',
            'articlename' => 'Strandtuch "Ibiza"',
            'articleID' => '178',
            'ordernumber' => 'SW10178',
            'shippingfree' => '0',
            'quantity' => '10',
            'price' => '16,765',
            'netprice' => '16.765',
            'tax_rate' => '19',
            'datum' => '2022-07-12 14:19:31',
            'modus' => '0',
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => '',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => 'Stück',
            'mainDetailId' => '407',
            'articleDetailId' => '407',
            'minpurchase' => '1',
            'taxID' => '1',
            'instock' => '84',
            'suppliernumber' => '',
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'laststock' => '0',
            'shippingtime' => '',
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => '',
            'stockmin' => '0',
            'ob_attr1' => '',
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => [
                'articleID' => 178,
                'articleDetailsID' => 407,
                'ordernumber' => 'SW10178',
                'highlight' => false,
                'description' => 'paulatim Praecepio lex Edoceo sis conticinium Furtum Heidelberg casula Toto pes an jugiter pe.',
                'description_long' => '',
                'esd' => false,
                'articleName' => 'Strandtuch "Ibiza"',
                'taxID' => 1,
                'tax' => 19.0,
                'instock' => 84,
                'isAvailable' => true,
                'weight' => 0.0,
                'shippingtime' => null,
                'pricegroupActive' => false,
                'pricegroupID' => null,
                'length' => 0.0,
                'height' => 0.0,
                'width' => 0.0,
                'laststock' => false,
                'additionaltext' => '',
                'datum' => '2012-08-21',
                'sales' => 0,
                'filtergroupID' => null,
                'priceStartingFrom' => null,
                'pseudopricePercent' => null,
                'sVariantArticle' => null,
                'sConfigurator' => false,
                'metaTitle' => null,
                'shippingfree' => false,
                'suppliernumber' => '',
                'notification' => false,
                'ean' => '',
                'keywords' => '',
                'sReleasedate' => '',
                'template' => '',
                'allowBuyInListing' => true,
                'attr1' => '',
                'attr2' => '',
                'attr3' => '',
                'attr4' => '',
                'attr5' => '',
                'attr6' => '',
                'attr7' => '',
                'attr8' => '',
                'attr9' => '',
                'attr10' => '',
                'attr11' => '',
                'attr12' => '',
                'attr13' => '',
                'attr14' => '',
                'attr15' => '',
                'attr16' => '',
                'attr17' => null,
                'attr18' => '',
                'attr19' => '',
                'attr20' => '',
                'supplierName' => 'Beachdreams Clothes',
                'supplierID' => 12,
                'supplierDescription' => '',
                'supplier_attributes' => [],
                'newArticle' => false,
                'sUpcoming' => false,
                'topseller' => false,
                'valFrom' => 1,
                'valTo' => null,
                'from' => 1,
                'to' => null,
                'price' => '16,77',
                'pseudoprice' => '0',
                'referenceprice' => '0',
                'has_pseudoprice' => false,
                'price_numeric' => 16.765,
                'pseudoprice_numeric' => 0.0,
                'price_attributes' => [],
                'pricegroup' => 'EK',
                'minpurchase' => 1,
                'maxpurchase' => '100',
                'purchasesteps' => 1,
                'purchaseunit' => null,
                'referenceunit' => null,
                'packunit' => 'Stück',
                'unitID' => null,
                'sUnit' => [
                    'unit' => null,
                    'description' => null,
                ],
                'unit_attributes' => [],
                'prices' => [
                    [
                        'valFrom' => 1,
                        'valTo' => null,
                        'from' => 1,
                        'to' => null,
                        'price' => '16,77',
                        'pseudoprice' => '0',
                        'referenceprice' => '0',
                        'pseudopricePercent' => null,
                        'has_pseudoprice' => false,
                        'price_numeric' => 16.765,
                        'pseudoprice_numeric' => 0.0,
                        'price_attributes' => [],
                        'pricegroup' => 'EK',
                        'minpurchase' => 1,
                        'maxpurchase' => '100',
                        'purchasesteps' => 1,
                        'purchaseunit' => null,
                        'referenceunit' => null,
                        'packunit' => 'Stück',
                        'unitID' => null,
                        'sUnit' => [
                            'unit' => null,
                            'description' => null,
                        ],
                        'unit_attributes' => [],
                    ],
                ],
                'linkBasket' => 'shopware.php?sViewport=basket&sAdd=SW10178',
                'linkDetails' => 'shopware.php?sViewport=detail&sArticle=178',
                'linkVariant' => 'shopware.php?sViewport=detail&sArticle=178&number=SW10178',
            ],
            'amountWithTax' => 199.563,
            'amount' => '167,70',
            'amountnet' => '167,70',
            'priceNumeric' => '16.765',
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=178',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=670',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW10178',
            'tax' => '31,86',
        ],
        [
            'id' => '805',
            'sessionID' => '2glivht14j7tl61bp793si4bjg',
            'userID' => '0',
            'articlename' => '-5 % Warenkorbrabatt',
            'articleID' => '0',
            'ordernumber' => 'sw-discount',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '-8,39',
            'netprice' => '-8.39',
            'tax_rate' => '19',
            'datum' => '2022-07-13 09:07:50',
            'modus' => '3',
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => '',
            'useragent' => '',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'laststock' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'shippinginfo' => false,
            'esd' => '0',
            'amountWithTax' => -9.98,
            'amount' => '-8,39',
            'amountnet' => '-8,39',
            'priceNumeric' => '-8.39',
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=0',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=805',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=sw-discount',
            'tax' => '-1,59',
        ],
    ],
    'Amount' => '159,31',
    'AmountNet' => '159,31',
    'Quantity' => 1,
    'AmountNumeric' => 159.31,
    'AmountNetNumeric' => 159.31,
    'AmountWithTax' => '189,58',
    'AmountWithTaxNumeric' => 189.58,
    'sCurrencyId' => 1,
    'sCurrencyName' => 'EUR',
    'sShippingcostsWithTax' => 0,
    'sShippingcostsNet' => 0,
    'sShippingcostsTax' => null,
    'sTaxRates' => [
        '19.00' => 30.27,
    ],
    'sShippingcosts' => 0,
    'sAmount' => 159.31,
    'sAmountTax' => 30.27,
    'sAmountWithTax' => 189.58,
];
