<?php
/**
 * (c) shopware AG <info@shopware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'content' => [
            0 => [
                    'id' => 700,
                    'sessionID' => 'ad5bdece48af0f1c1c4fc044f1c638dc',
                    'userID' => 1,
                    'articlename' => 'Strandtuch "Ibiza"',
                    'articleID' => 178,
                    'ordernumber' => 'SW10178',
                    'shippingfree' => 0,
                    'quantity' => 1,
                    'price' => '19,95',
                    'netprice' => 16.764705882352999,
                    'tax_rate' => 19.0,
                    'datum' => '2022-04-12 14:22:09',
                    'modus' => 0,
                    'esdarticle' => 0,
                    'partnerID' => '',
                    'lastviewport' => 'index',
                    'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36',
                    'config' => '',
                    'currencyFactor' => 1.0,
                    'packunit' => 'Stück',
                    'mainDetailId' => 407,
                    'articleDetailId' => 407,
                    'minpurchase' => 1,
                    'taxID' => 1,
                    'instock' => 80,
                    'suppliernumber' => '',
                    'maxpurchase' => '100',
                    'purchasesteps' => 1,
                    'purchaseunit' => null,
                    'laststock' => 0,
                    'shippingtime' => null,
                    'releasedate' => null,
                    'sReleaseDate' => null,
                    'ean' => '',
                    'stockmin' => 0,
                    'ob_attr1' => '',
                    'ob_attr2' => null,
                    'ob_attr3' => null,
                    'ob_attr4' => null,
                    'ob_attr5' => null,
                    'ob_attr6' => null,
                    '__s_order_basket_attributes_id' => 40,
                    '__s_order_basket_attributes_basketID' => 700,
                    '__s_order_basket_attributes_attribute1' => '',
                    '__s_order_basket_attributes_attribute2' => null,
                    '__s_order_basket_attributes_attribute3' => null,
                    '__s_order_basket_attributes_attribute4' => null,
                    '__s_order_basket_attributes_attribute5' => null,
                    '__s_order_basket_attributes_attribute6' => null,
                    'shippinginfo' => true,
                    'esd' => 0,
                    'additional_details' => [
                            'articleID' => 178,
                            'articleDetailsID' => 407,
                            'ordernumber' => 'SW10178',
                            'highlight' => false,
                            'description' => 'paulatim Praecepio lex Edoceo sis conticinium Furtum Heidelberg casula Toto pes an jugiter pe.',
                            'description_long' => '
o decertatio. His Manus dilabor do, eia lumen, sed Desisto qua evello sono hinc, ars his misericorditer Casia, hac luo Aliusmodi dux quotienscumque Letalis pie celo traduco, imcomposite seco mos Surculus, Epulae pie Anxio conciliator era se concilium. Terra quam dicto erro prolecto, quo per incommoditas paulatim Praecepio lex Edoceo sis conticinium Furtum Heidelberg casula Toto pes an jugiter pe.

',
                            'esd' => false,
                            'articleName' => 'Strandtuch "Ibiza"',
                            'taxID' => 1,
                            'tax' => 19.0,
                            'instock' => 80,
                            'isAvailable' => true,
                            'hasAvailableVariant' => true,
                            'weight' => 0.0,
                            'shippingtime' => null,
                            'pricegroupActive' => false,
                            'pricegroupID' => null,
                            'length' => 0.0,
                            'height' => 0.0,
                            'width' => 0.0,
                            'laststock' => false,
                            'additionaltext' => '',
                            'datum' => '2012-08-21',
                            'update' => '2012-08-31',
                            'sales' => 4,
                            'filtergroupID' => null,
                            'priceStartingFrom' => null,
                            'pseudopricePercent' => null,
                            'sVariantArticle' => null,
                            'sConfigurator' => false,
                            'metaTitle' => null,
                            'shippingfree' => false,
                            'suppliernumber' => '',
                            'notification' => false,
                            'ean' => '',
                            'keywords' => '',
                            'sReleasedate' => '',
                            'template' => '',
                            'attributes' => [
                                    'core' => [
                                        'storage' => [
                                                'id' => 429,
                                                'articledetailsID' => 407,
                                                'attr1' => '',
                                                'attr2' => '',
                                                'attr3' => '',
                                                'attr4' => '',
                                                'attr5' => '',
                                                'attr6' => '',
                                                'attr7' => '',
                                                'attr8' => '',
                                                'attr9' => '',
                                                'attr10' => '',
                                                'attr11' => '',
                                                'attr12' => '',
                                                'attr13' => '',
                                                'attr14' => '',
                                                'attr15' => '',
                                                'attr16' => '',
                                                'attr17' => null,
                                                'attr18' => '',
                                                'attr19' => '',
                                                'attr20' => '',
                                            ],
                                    ],
                                    'marketing' => [],
                                ],
                            'allowBuyInListing' => true,
                            'attr1' => '',
                            'attr2' => '',
                            'attr3' => '',
                            'attr4' => '',
                            'attr5' => '',
                            'attr6' => '',
                            'attr7' => '',
                            'attr8' => '',
                            'attr9' => '',
                            'attr10' => '',
                            'attr11' => '',
                            'attr12' => '',
                            'attr13' => '',
                            'attr14' => '',
                            'attr15' => '',
                            'attr16' => '',
                            'attr17' => null,
                            'attr18' => '',
                            'attr19' => '',
                            'attr20' => '',
                            'supplierName' => 'Beachdreams Clothes',
                            'supplierImg' => 'http://shopware.localhost/media/image/a1/f7/82/beachdreams.png',
                            'supplierID' => 12,
                            'supplierDescription' => '',
                            'supplierMedia' => [
                                    'id' => 666,
                                    'position' => null,
                                    'source' => 'http://shopware.localhost/media/image/a1/f7/82/beachdreams.png',
                                    'description' => 'beachdreams',
                                    'extension' => 'png',
                                    'main' => null,
                                    'parentId' => null,
                                    'width' => 204,
                                    'height' => 85,
                                    'thumbnails' => [
                                            0 => [
                                                    'source' => 'http://shopware.localhost/media/image/95/da/c8/beachdreams_200x200.png',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/83/c0/5c/beachdreams_200x200@2x.png',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/95/da/c8/beachdreams_200x200.png, http://shopware.localhost/media/image/83/c0/5c/beachdreams_200x200@2x.png 2x',
                                                    'maxWidth' => '200',
                                                    'maxHeight' => '200',
                                                    'attributes' => [
                                                        ],
                                                ],
                                            1 => [
                                                    'source' => 'http://shopware.localhost/media/image/60/3d/67/beachdreams_600x600.png',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/9b/c0/49/beachdreams_600x600@2x.png',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/60/3d/67/beachdreams_600x600.png, http://shopware.localhost/media/image/9b/c0/49/beachdreams_600x600@2x.png 2x',
                                                    'maxWidth' => '600',
                                                    'maxHeight' => '600',
                                                    'attributes' => [
                                                        ],
                                                ],
                                            2 => [
                                                    'source' => 'http://shopware.localhost/media/image/3f/32/20/beachdreams_1280x1280.png',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/b9/3b/25/beachdreams_1280x1280@2x.png',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/3f/32/20/beachdreams_1280x1280.png, http://shopware.localhost/media/image/b9/3b/25/beachdreams_1280x1280@2x.png 2x',
                                                    'maxWidth' => '1280',
                                                    'maxHeight' => '1280',
                                                    'attributes' => [
                                                        ],
                                                ],
                                        ],
                                    'attributes' => [
                                        ],
                                    'attribute' => [
                                        ],
                                ],
                            'supplier_attributes' => [
                                ],
                            'newArticle' => false,
                            'sUpcoming' => false,
                            'topseller' => false,
                            'valFrom' => 1,
                            'valTo' => null,
                            'from' => 1,
                            'to' => null,
                            'price' => '19,95',
                            'pseudoprice' => '0',
                            'referenceprice' => '0',
                            'has_pseudoprice' => false,
                            'price_numeric' => 19.949999999999999,
                            'pseudoprice_numeric' => 0.0,
                            'price_attributes' => [
                                ],
                            'pricegroup' => 'EK',
                            'regulationPrice' => null,
                            'minpurchase' => 1,
                            'maxpurchase' => '100',
                            'purchasesteps' => 1,
                            'purchaseunit' => null,
                            'referenceunit' => null,
                            'packunit' => 'Stück',
                            'unitID' => null,
                            'sUnit' => [
                                    'unit' => null,
                                    'description' => null,
                                ],
                            'unit_attributes' => [
                                ],
                            'image' => [
                                    'id' => 445,
                                    'position' => null,
                                    'source' => 'http://shopware.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                                    'description' => '',
                                    'extension' => 'jpg',
                                    'main' => true,
                                    'parentId' => null,
                                    'width' => 1698,
                                    'height' => 1131,
                                    'thumbnails' => [
                                            0 => [
                                                    'source' => 'http://shopware.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg, http://shopware.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg 2x',
                                                    'maxWidth' => '200',
                                                    'maxHeight' => '200',
                                                    'attributes' => [
                                                        ],
                                                ],
                                            1 => [
                                                    'source' => 'http://shopware.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg, http://shopware.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg 2x',
                                                    'maxWidth' => '600',
                                                    'maxHeight' => '600',
                                                    'attributes' => [
                                                        ],
                                                ],
                                            2 => [
                                                    'source' => 'http://shopware.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg, http://shopware.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg 2x',
                                                    'maxWidth' => '1280',
                                                    'maxHeight' => '1280',
                                                    'attributes' => [
                                                        ],
                                                ],
                                        ],
                                    'attributes' => [
                                        ],
                                    'attribute' => [
                                        ],
                                ],
                            'prices' => [
                                    0 => [
                                            'valFrom' => 1,
                                            'valTo' => null,
                                            'from' => 1,
                                            'to' => null,
                                            'price' => '19,95',
                                            'pseudoprice' => '0',
                                            'referenceprice' => '0',
                                            'pseudopricePercent' => null,
                                            'has_pseudoprice' => false,
                                            'price_numeric' => 19.949999999999999,
                                            'pseudoprice_numeric' => 0.0,
                                            'price_attributes' => [
                                                ],
                                            'pricegroup' => 'EK',
                                            'regulationPrice' => null,
                                            'minpurchase' => 1,
                                            'maxpurchase' => '100',
                                            'purchasesteps' => 1,
                                            'purchaseunit' => null,
                                            'referenceunit' => null,
                                            'packunit' => 'Stück',
                                            'unitID' => null,
                                            'sUnit' => [
                                                    'unit' => null,
                                                    'description' => null,
                                                ],
                                            'unit_attributes' => [
                                                ],
                                        ],
                                ],
                            'linkBasket' => 'shopware.php?sViewport=basket&sAdd=SW10178',
                            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=178',
                            'linkVariant' => 'shopware.php?sViewport=detail&sArticle=178&number=SW10178',
                        ],
                    'amount' => '19,95',
                    'amountnet' => '16,76',
                    'priceNumeric' => 19.949999999999999,
                    'amountNumeric' => 19.949999999999999,
                    'amountnetNumeric' => 16.764705882352999,
                    'image' => [
                            'id' => 445,
                            'position' => null,
                            'source' => 'http://shopware.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                            'description' => '',
                            'extension' => 'jpg',
                            'main' => true,
                            'parentId' => null,
                            'width' => 1698,
                            'height' => 1131,
                            'thumbnails' => [
                                    0 => [
                                            'source' => 'http://shopware.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                                            'retinaSource' => 'http://shopware.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                                            'sourceSet' => 'http://shopware.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg, http://shopware.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg 2x',
                                            'maxWidth' => '200',
                                            'maxHeight' => '200',
                                            'attributes' => [
                                                ],
                                        ],
                                    1 => [
                                            'source' => 'http://shopware.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                                            'retinaSource' => 'http://shopware.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                                            'sourceSet' => 'http://shopware.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg, http://shopware.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg 2x',
                                            'maxWidth' => '600',
                                            'maxHeight' => '600',
                                            'attributes' => [
                                                ],
                                        ],
                                    2 => [
                                            'source' => 'http://shopware.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                                            'retinaSource' => 'http://shopware.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                                            'sourceSet' => 'http://shopware.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg, http://shopware.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg 2x',
                                            'maxWidth' => '1280',
                                            'maxHeight' => '1280',
                                            'attributes' => [
                                                ],
                                        ],
                                ],
                            'attributes' => [
                                ],
                            'attribute' => [
                                ],
                            'src' => [
                                    'original' => 'http://shopware.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                                    0 => 'http://shopware.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                                    1 => 'http://shopware.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                                    2 => 'http://shopware.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                                ],
                            'srchd' => [
                                    'original' => 'http://shopware.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                                    0 => 'http://shopware.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                                    1 => 'http://shopware.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                                    2 => 'http://shopware.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                                ],
                            'res' => [
                                    'original' => [
                                            'width' => 1131,
                                            'height' => 1698,
                                        ],
                                ],
                        ],
                    'linkDetails' => 'shopware.php?sViewport=detail&sArticle=178',
                    'linkDelete' => 'shopware.php?sViewport=basket&sDelete=700',
                    'linkNote' => 'shopware.php?sViewport=note&sAdd=SW10178',
                    'tax' => '3,19',
                ],
        ],
    'Amount' => '19,95',
    'AmountNet' => '16,76',
    'Quantity' => 1,
    'AmountNumeric' => 45.939999999999998,
    'AmountNetNumeric' => 38.600000000000001,
    'AmountWithTax' => '0',
    'AmountWithTaxNumeric' => 0.0,
    'sCurrencyId' => 1,
    'sCurrencyName' => 'EUR',
    'sCurrencyFactor' => 1.0,
    'sShippingcostsWithTax' => 25.989999999999998,
    'sShippingcostsNet' => 21.84,
    'sShippingcostsTax' => 19.0,
    'sShippingcostsDifference' => 9980.0499999999993,
    'sTaxRates' => [
            '19.00' => 7.3399999999999981,
        ],
    'sShippingcosts' => 25.989999999999998,
    'sAmount' => 45.939999999999998,
    'sAmountTax' => 7.3399999999999999,
];
