<?php
/**
 * (c) shopware AG <info@shopware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'billingaddress' => [
            'id' => 5,
            'company' => null,
            'department' => null,
            'salutation' => 'mr',
            'firstname' => 'PhpUnit',
            'title' => null,
            'lastname' => 'Tester',
            'street' => 'FooBarStreet, 42',
            'zipcode' => '12345',
            'city' => 'SinCity',
            'phone' => '123456789',
            'vatId' => null,
            'additionalAddressLine1' => null,
            'additionalAddressLine2' => null,
            'countryId' => 2,
            'stateId' => null,
            'customer' => [
                    'id' => 3,
                ],
            'country' => [
                    'id' => 2,
                ],
            'state' => null,
            'userID' => 3,
            'countryID' => 2,
            'stateID' => null,
            'ustid' => null,
            'additional_address_line1' => null,
            'additional_address_line2' => null,
            'attributes' => [
                    'id' => '3',
                    'address_id' => '5',
                    'text1' => null,
                    'text2' => null,
                    'text3' => null,
                    'text4' => null,
                    'text5' => null,
                    'text6' => null,
                ],
        ],
    'additional' => [
            'country' => [
                    'id' => '2',
                    'countryname' => 'Deutschland',
                    'countryiso' => 'DE',
                    'areaID' => '1',
                    'countryen' => 'GERMANY',
                    'position' => '1',
                    'notice' => '',
                    'taxfree' => '0',
                    'taxfree_ustid' => '0',
                    'taxfree_ustid_checked' => '0',
                    'active' => '1',
                    'iso3' => 'DEU',
                    'display_state_in_registration' => '0',
                    'force_state_in_registration' => '0',
                    'allow_shipping' => '1',
                    'countryarea' => 'deutschland',
                ],
            'state' => [
                ],
            'user' => [
                    'id' => '3',
                    'userID' => '3',
                    'password' => '$2y$10$GTCr6Y6saAGWQwG2eQntoevo7bxAtNUf2b2o/xDF3qlvOK.IMncuu',
                    'encoder' => 'bcrypt',
                    'email' => 'phpUnit.tester@test.com',
                    'active' => '1',
                    'accountmode' => '0',
                    'confirmationkey' => '',
                    'paymentID' => '7',
                    'doubleOptinRegister' => '0',
                    'doubleOptinEmailSentDate' => null,
                    'doubleOptinConfirmDate' => null,
                    'firstlogin' => '2022-01-05',
                    'lastlogin' => '2022-01-05 07:35:39',
                    'sessionID' => '9219869a66e0a4d45be2c7d48f234bfd',
                    'newsletter' => 0,
                    'validation' => '',
                    'affiliate' => '0',
                    'customergroup' => 'EK',
                    'paymentpreset' => '0',
                    'language' => '1',
                    'subshopID' => '1',
                    'referer' => '',
                    'pricegroupID' => null,
                    'internalcomment' => '',
                    'failedlogins' => '0',
                    'lockeduntil' => null,
                    'default_billing_address_id' => '5',
                    'default_shipping_address_id' => '5',
                    'title' => null,
                    'salutation' => 'mr',
                    'firstname' => 'PhpUnit',
                    'lastname' => 'Tester',
                    'birthday' => '1970-01-01',
                    'customernumber' => '20005',
                    'login_token' => '23c88e33-9caa-4795-a2d9-7df4e5bd54ea.1',
                    'changed' => '2022-01-05 08:21:43',
                    'password_change_date' => '2022-01-05 08:21:43',
                    'register_opt_in_id' => null,
                ],
            'countryShipping' => [
                    'id' => '2',
                    'countryname' => 'Deutschland',
                    'countryiso' => 'DE',
                    'areaID' => '1',
                    'countryen' => 'GERMANY',
                    'position' => '1',
                    'notice' => '',
                    'taxfree' => '0',
                    'taxfree_ustid' => '0',
                    'taxfree_ustid_checked' => '0',
                    'active' => '1',
                    'iso3' => 'DEU',
                    'display_state_in_registration' => '0',
                    'force_state_in_registration' => '0',
                    'allow_shipping' => '1',
                    'countryarea' => 'deutschland',
                ],
            'stateShipping' => [
                ],
            'payment' => [
                    'id' => '7',
                    'name' => 'SwagPaymentPayPalUnified',
                    'description' => 'PayPal',
                    'template' => '',
                    'class' => '',
                    'table' => '',
                    'hide' => '0',
                    'additionaldescription' => 'Logo \'PayPal empfohlen\'
Bezahlung per PayPal - einfach, schnell und sicher.',
                    'debit_percent' => '0',
                    'surcharge' => '0',
                    'surchargestring' => '',
                    'position' => '-100',
                    'active' => '1',
                    'esdactive' => '0',
                    'embediframe' => '',
                    'hideprospect' => '0',
                    'action' => 'PaypalUnifiedV2',
                    'pluginID' => null,
                    'source' => null,
                    'mobile_inactive' => '0',
                    'attributes' => [
                        ],
                    'validation' => [
                        ],
                ],
            'charge_vat' => true,
            'show_net' => true,
        ],
    'shippingaddress' => [
            'id' => 5,
            'company' => null,
            'department' => null,
            'salutation' => 'mr',
            'firstname' => 'PhpUnit',
            'title' => null,
            'lastname' => 'Tester',
            'street' => 'FooBarStreet, 42',
            'zipcode' => '12345',
            'city' => 'SinCity',
            'phone' => '123456789',
            'vatId' => null,
            'additionalAddressLine1' => null,
            'additionalAddressLine2' => null,
            'countryId' => 2,
            'stateId' => null,
            'customer' => [
                    'id' => 3,
                ],
            'country' => [
                    'id' => 2,
                ],
            'state' => null,
            'userID' => 3,
            'countryID' => 2,
            'stateID' => null,
            'ustid' => null,
            'additional_address_line1' => null,
            'additional_address_line2' => null,
            'attributes' => [
                    'id' => '3',
                    'address_id' => '5',
                    'text1' => null,
                    'text2' => null,
                    'text3' => null,
                    'text4' => null,
                    'text5' => null,
                    'text6' => null,
                ],
        ],
];
