<?php
/**
 * (c) shopware AG <info@shopware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'content' => [
            0 => [
                    'id' => 670,
                    'sessionID' => 'd3b2438f074f9fd2d9f5ef3621e06f0b',
                    'userID' => 1,
                    'articlename' => 'Cigar Special 40%',
                    'articleID' => 6,
                    'ordernumber' => 'SW10006',
                    'shippingfree' => 0,
                    'quantity' => 1,
                    'price' => '35,95',
                    'netprice' => 30.210084033613001,
                    'tax_rate' => 19.0,
                    'datum' => '2022-04-05 08:16:13',
                    'modus' => 0,
                    'esdarticle' => 0,
                    'partnerID' => '',
                    'lastviewport' => 'checkout',
                    'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36',
                    'config' => '',
                    'currencyFactor' => 1.0,
                    'packunit' => 'Flasche(n)',
                    'mainDetailId' => 6,
                    'articleDetailId' => 6,
                    'minpurchase' => 1,
                    'taxID' => 1,
                    'instock' => 20,
                    'suppliernumber' => '',
                    'maxpurchase' => '100',
                    'purchasesteps' => 1,
                    'purchaseunit' => '0.5000',
                    'unitID' => 1,
                    'laststock' => 0,
                    'shippingtime' => null,
                    'releasedate' => null,
                    'sReleaseDate' => null,
                    'ean' => null,
                    'stockmin' => 0,
                    'ob_attr1' => '',
                    'ob_attr2' => null,
                    'ob_attr3' => null,
                    'ob_attr4' => null,
                    'ob_attr5' => null,
                    'ob_attr6' => null,
                    '__s_order_basket_attributes_id' => 33,
                    '__s_order_basket_attributes_basketID' => 670,
                    '__s_order_basket_attributes_attribute1' => '',
                    '__s_order_basket_attributes_attribute2' => null,
                    '__s_order_basket_attributes_attribute3' => null,
                    '__s_order_basket_attributes_attribute4' => null,
                    '__s_order_basket_attributes_attribute5' => null,
                    '__s_order_basket_attributes_attribute6' => null,
                    'shippinginfo' => true,
                    'esd' => 0,
                    'additional_details' => [
                            'articleID' => 6,
                            'articleDetailsID' => 6,
                            'ordernumber' => 'SW10006',
                            'highlight' => false,
                            'description' => 'O barbaricus poeta Casus dum dis tueor iam Basilicus cur ne duo de neglectum, ut heu Fera hic Profiteor. Ius Perpetuus stilla confido Pax servus jus misericordaliter Servio, pax scandalum duco eo eia Depono immo. ',
                            'description_long' => '
A De cum casa fiducialiter laboriosus Secundus, lex asper ros hio cur interrogatio saltem vir Adversa, Gregatim mei Eo metuo sum maro iam proclivia amicabiliter occulto cruor fleo peto delitesco Comperte lacerta his tot Os ut Fruor res Gaza provisio conscientia dux effrenus Promus sui secundus rutila. Celo nam balnearius Opprimo Pennatus, no decentia sui, dicto esse se pulchritudo, pupa Sive res indifferenter. Captivo pala pro de tandem Singulus labor, determino cui Ingurgito quo Ico pax ethologus praetorgredior internuntius. Ops foveo Huius dux respublica his animadverto dolus imperterritus. Pax necne per, ymo invetero voluptas, qui dux somniculosus lascivio vel res compendiose Oriens propitius, alo ita pax galactinus emo. Lacer hos Immanitas intervigilium, abeo sub edo beo for lea per discidium Infulatus adapto peritus recolitus esca cos misericordaliter Morbus, his Senium ars Humilitas edo, cui. Sis sacrilegus Fatigo almus vae excedo, aut vegetabiliter Erogo villa periclitatus, for.

',
                            'esd' => false,
                            'articleName' => 'Cigar Special 40%',
                            'taxID' => 1,
                            'tax' => 19.0,
                            'instock' => 20,
                            'isAvailable' => true,
                            'hasAvailableVariant' => true,
                            'weight' => 0.0,
                            'shippingtime' => null,
                            'pricegroupActive' => false,
                            'pricegroupID' => null,
                            'length' => 0.0,
                            'height' => 0.0,
                            'width' => 0.0,
                            'laststock' => false,
                            'additionaltext' => '',
                            'datum' => '2012-08-15',
                            'update' => '2012-08-20',
                            'sales' => 0,
                            'filtergroupID' => 1,
                            'priceStartingFrom' => null,
                            'pseudopricePercent' => null,
                            'sVariantArticle' => null,
                            'sConfigurator' => false,
                            'metaTitle' => null,
                            'shippingfree' => false,
                            'suppliernumber' => '',
                            'notification' => false,
                            'ean' => '',
                            'keywords' => '',
                            'sReleasedate' => '',
                            'template' => '',
                            'attributes' => [
                                    'core' => [
                                            'storage' => [
                                                    'id' => 6,
                                                    'articledetailsID' => 6,
                                                    'attr1' => '',
                                                    'attr2' => '',
                                                    'attr3' => '',
                                                    'attr4' => '',
                                                    'attr5' => '',
                                                    'attr6' => '',
                                                    'attr7' => '',
                                                    'attr8' => '',
                                                    'attr9' => '',
                                                    'attr10' => '',
                                                    'attr11' => '',
                                                    'attr12' => '',
                                                    'attr13' => '',
                                                    'attr14' => '',
                                                    'attr15' => '',
                                                    'attr16' => '',
                                                    'attr17' => null,
                                                    'attr18' => '',
                                                    'attr19' => '',
                                                    'attr20' => '',
                                                ],
                                        ],
                                ],
                            'allowBuyInListing' => true,
                            'attr1' => '',
                            'attr2' => '',
                            'attr3' => '',
                            'attr4' => '',
                            'attr5' => '',
                            'attr6' => '',
                            'attr7' => '',
                            'attr8' => '',
                            'attr9' => '',
                            'attr10' => '',
                            'attr11' => '',
                            'attr12' => '',
                            'attr13' => '',
                            'attr14' => '',
                            'attr15' => '',
                            'attr16' => '',
                            'attr17' => null,
                            'attr18' => '',
                            'attr19' => '',
                            'attr20' => '',
                            'supplierName' => 'Feinbrennerei Sasse',
                            'supplierImg' => 'http://shopware.localhost/media/image/52/5b/a1/sasse.png',
                            'supplierID' => 2,
                            'supplierDescription' => '',
                            'supplierMedia' => [
                                    'id' => 670,
                                    'position' => null,
                                    'source' => 'http://shopware.localhost/media/image/52/5b/a1/sasse.png',
                                    'description' => 'sasse',
                                    'extension' => 'png',
                                    'main' => null,
                                    'parentId' => null,
                                    'width' => 204,
                                    'height' => 85,
                                    'thumbnails' => [
                                            0 => [
                                                    'source' => 'http://shopware.localhost/media/image/01/82/69/sasse_200x200.png',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/78/1d/0c/sasse_200x200@2x.png',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/01/82/69/sasse_200x200.png, http://shopware.localhost/media/image/78/1d/0c/sasse_200x200@2x.png 2x',
                                                    'maxWidth' => '200',
                                                    'maxHeight' => '200',
                                                    'attributes' => [
                                                        ],
                                                ],
                                            1 => [
                                                    'source' => 'http://shopware.localhost/media/image/6e/a9/11/sasse_600x600.png',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/9c/1d/19/sasse_600x600@2x.png',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/6e/a9/11/sasse_600x600.png, http://shopware.localhost/media/image/9c/1d/19/sasse_600x600@2x.png 2x',
                                                    'maxWidth' => '600',
                                                    'maxHeight' => '600',
                                                    'attributes' => [
                                                        ],
                                                ],
                                            2 => [
                                                    'source' => 'http://shopware.localhost/media/image/55/12/76/sasse_1280x1280.png',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/30/4b/6b/sasse_1280x1280@2x.png',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/55/12/76/sasse_1280x1280.png, http://shopware.localhost/media/image/30/4b/6b/sasse_1280x1280@2x.png 2x',
                                                    'maxWidth' => '1280',
                                                    'maxHeight' => '1280',
                                                    'attributes' => [
                                                        ],
                                                ],
                                        ],
                                    'attributes' => [
                                        ],
                                    'attribute' => [
                                        ],
                                ],
                            'supplier_attributes' => [
                                ],
                            'newArticle' => false,
                            'sUpcoming' => false,
                            'topseller' => false,
                            'valFrom' => 1,
                            'valTo' => null,
                            'from' => 1,
                            'to' => null,
                            'price' => '35,95',
                            'pseudoprice' => '0',
                            'referenceprice' => '71,90',
                            'has_pseudoprice' => false,
                            'price_numeric' => 35.950000000000003,
                            'pseudoprice_numeric' => 0.0,
                            'price_attributes' => [
                                ],
                            'pricegroup' => 'EK',
                            'regulationPrice' => null,
                            'minpurchase' => 1,
                            'maxpurchase' => '100',
                            'purchasesteps' => 1,
                            'purchaseunit' => 0.5,
                            'referenceunit' => 1.0,
                            'packunit' => 'Flasche(n)',
                            'unitID' => 1,
                            'sUnit' => [
                                    'unit' => 'l',
                                    'description' => 'Liter',
                                ],
                            'unit_attributes' => [
                                ],
                            'image' => [
                                    'id' => 16,
                                    'position' => null,
                                    'source' => 'http://shopware.localhost/media/image/bf/b2/1f/Cigar_Special.jpg',
                                    'description' => '',
                                    'extension' => 'jpg',
                                    'main' => true,
                                    'parentId' => null,
                                    'width' => 1380,
                                    'height' => 3588,
                                    'thumbnails' => [
                                            0 => [
                                                    'source' => 'http://shopware.localhost/media/image/e5/c3/71/Cigar_Special_200x200.jpg',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/c3/76/c3/Cigar_Special_200x200@2x.jpg',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/e5/c3/71/Cigar_Special_200x200.jpg, http://shopware.localhost/media/image/c3/76/c3/Cigar_Special_200x200@2x.jpg 2x',
                                                    'maxWidth' => '200',
                                                    'maxHeight' => '200',
                                                    'attributes' => [
                                                        ],
                                                ],
                                            1 => [
                                                    'source' => 'http://shopware.localhost/media/image/3a/5d/7d/Cigar_Special_600x600.jpg',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/e6/c1/11/Cigar_Special_600x600@2x.jpg',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/3a/5d/7d/Cigar_Special_600x600.jpg, http://shopware.localhost/media/image/e6/c1/11/Cigar_Special_600x600@2x.jpg 2x',
                                                    'maxWidth' => '600',
                                                    'maxHeight' => '600',
                                                    'attributes' => [
                                                        ],
                                                ],
                                            2 => [
                                                    'source' => 'http://shopware.localhost/media/image/cb/c5/15/Cigar_Special_1280x1280.jpg',
                                                    'retinaSource' => 'http://shopware.localhost/media/image/f3/14/54/Cigar_Special_1280x1280@2x.jpg',
                                                    'sourceSet' => 'http://shopware.localhost/media/image/cb/c5/15/Cigar_Special_1280x1280.jpg, http://shopware.localhost/media/image/f3/14/54/Cigar_Special_1280x1280@2x.jpg 2x',
                                                    'maxWidth' => '1280',
                                                    'maxHeight' => '1280',
                                                    'attributes' => [
                                                        ],
                                                ],
                                        ],
                                    'attributes' => [
                                        ],
                                    'attribute' => [
                                        ],
                                ],
                            'prices' => [
                                    0 => [
                                            'valFrom' => 1,
                                            'valTo' => null,
                                            'from' => 1,
                                            'to' => null,
                                            'price' => '35,95',
                                            'pseudoprice' => '0',
                                            'referenceprice' => '71,90',
                                            'pseudopricePercent' => null,
                                            'has_pseudoprice' => false,
                                            'price_numeric' => 35.950000000000003,
                                            'pseudoprice_numeric' => 0.0,
                                            'price_attributes' => [
                                                ],
                                            'pricegroup' => 'EK',
                                            'regulationPrice' => null,
                                            'minpurchase' => 1,
                                            'maxpurchase' => '100',
                                            'purchasesteps' => 1,
                                            'purchaseunit' => 0.5,
                                            'referenceunit' => 1.0,
                                            'packunit' => 'Flasche(n)',
                                            'unitID' => 1,
                                            'sUnit' => [
                                                    'unit' => 'l',
                                                    'description' => 'Liter',
                                                ],
                                            'unit_attributes' => [
                                                ],
                                        ],
                                ],
                            'linkBasket' => 'shopware.php?sViewport=basket&sAdd=SW10006',
                            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=6',
                            'linkVariant' => 'shopware.php?sViewport=detail&sArticle=6&number=SW10006',
                            'sProperties' => [
                                    7 => [
                                            'id' => 7,
                                            'optionID' => 7,
                                            'name' => 'Trinktemperatur',
                                            'groupID' => 1,
                                            'groupName' => 'Edelbrände',
                                            'value' => 'Zimmertemperatur',
                                            'values' => [
                                                    36 => 'Zimmertemperatur',
                                                ],
                                            'isFilterable' => true,
                                            'options' => [
                                                    0 => [
                                                            'id' => 36,
                                                            'name' => 'Zimmertemperatur',
                                                            'attributes' => [
                                                                ],
                                                        ],
                                                ],
                                            'media' => [
                                                ],
                                            'attributes' => [
                                                ],
                                        ],
                                    6 => [
                                            'id' => 6,
                                            'optionID' => 6,
                                            'name' => 'Geschmack',
                                            'groupID' => 1,
                                            'groupName' => 'Edelbrände',
                                            'value' => 'mild',
                                            'values' => [
                                                    33 => 'mild',
                                                ],
                                            'isFilterable' => true,
                                            'options' => [
                                                    0 => [
                                                            'id' => 33,
                                                            'name' => 'mild',
                                                            'attributes' => [
                                                                ],
                                                        ],
                                                ],
                                            'media' => [
                                                ],
                                            'attributes' => [
                                                ],
                                        ],
                                    2 => [
                                            'id' => 2,
                                            'optionID' => 2,
                                            'name' => 'Flaschengröße',
                                            'groupID' => 1,
                                            'groupName' => 'Edelbrände',
                                            'value' => '0,5 Liter',
                                            'values' => [
                                                    23 => '0,5 Liter',
                                                ],
                                            'isFilterable' => true,
                                            'options' => [
                                                    0 => [
                                                            'id' => 23,
                                                            'name' => '0,5 Liter',
                                                            'attributes' => [
                                                                ],
                                                        ],
                                                ],
                                            'media' => [
                                                ],
                                            'attributes' => [
                                                ],
                                        ],
                                    1 => [
                                            'id' => 1,
                                            'optionID' => 1,
                                            'name' => 'Alkoholgehalt',
                                            'groupID' => 1,
                                            'groupName' => 'Edelbrände',
                                            'value' => '>30%',
                                            'values' => [
                                                    40 => '>30%',
                                                ],
                                            'isFilterable' => true,
                                            'options' => [
                                                    0 => [
                                                            'id' => 40,
                                                            'name' => '>30%',
                                                            'attributes' => [
                                                                ],
                                                        ],
                                                ],
                                            'media' => [
                                                ],
                                            'attributes' => [
                                                ],
                                        ],
                                ],
                            'properties' => 'Trinktemperatur: Zimmertemperatur, Geschmack: mild, Flaschengröße: 0,5 Liter, Alkoholgehalt: >30%',
                        ],
                    'itemUnit' => 'Liter',
                    'amount' => '35,95',
                    'purchaseunitTemp' => '0.5000',
                    'itemInfo' => '0.5000 Liter / 35,95',
                    'itemInfoArray' => [
                            'reference' => 1,
                            'unit' => [
                                    'unit' => 'l',
                                    'description' => 'Liter',
                                ],
                            'price' => '35,95',
                        ],
                    'amountnet' => '30,21',
                    'priceNumeric' => 35.950000000000003,
                    'amountNumeric' => 35.950000000000003,
                    'amountnetNumeric' => 30.210084033613001,
                    'image' => [
                            'id' => 16,
                            'position' => null,
                            'source' => 'http://shopware.localhost/media/image/bf/b2/1f/Cigar_Special.jpg',
                            'description' => '',
                            'extension' => 'jpg',
                            'main' => true,
                            'parentId' => null,
                            'width' => 1380,
                            'height' => 3588,
                            'thumbnails' => [
                                    0 => [
                                            'source' => 'http://shopware.localhost/media/image/e5/c3/71/Cigar_Special_200x200.jpg',
                                            'retinaSource' => 'http://shopware.localhost/media/image/c3/76/c3/Cigar_Special_200x200@2x.jpg',
                                            'sourceSet' => 'http://shopware.localhost/media/image/e5/c3/71/Cigar_Special_200x200.jpg, http://shopware.localhost/media/image/c3/76/c3/Cigar_Special_200x200@2x.jpg 2x',
                                            'maxWidth' => '200',
                                            'maxHeight' => '200',
                                            'attributes' => [
                                                ],
                                        ],
                                    1 => [
                                            'source' => 'http://shopware.localhost/media/image/3a/5d/7d/Cigar_Special_600x600.jpg',
                                            'retinaSource' => 'http://shopware.localhost/media/image/e6/c1/11/Cigar_Special_600x600@2x.jpg',
                                            'sourceSet' => 'http://shopware.localhost/media/image/3a/5d/7d/Cigar_Special_600x600.jpg, http://shopware.localhost/media/image/e6/c1/11/Cigar_Special_600x600@2x.jpg 2x',
                                            'maxWidth' => '600',
                                            'maxHeight' => '600',
                                            'attributes' => [
                                                ],
                                        ],
                                    2 => [
                                            'source' => 'http://shopware.localhost/media/image/cb/c5/15/Cigar_Special_1280x1280.jpg',
                                            'retinaSource' => 'http://shopware.localhost/media/image/f3/14/54/Cigar_Special_1280x1280@2x.jpg',
                                            'sourceSet' => 'http://shopware.localhost/media/image/cb/c5/15/Cigar_Special_1280x1280.jpg, http://shopware.localhost/media/image/f3/14/54/Cigar_Special_1280x1280@2x.jpg 2x',
                                            'maxWidth' => '1280',
                                            'maxHeight' => '1280',
                                            'attributes' => [
                                                ],
                                        ],
                                ],
                            'attributes' => [
                                ],
                            'attribute' => [
                                ],
                            'src' => [
                                    'original' => 'http://shopware.localhost/media/image/bf/b2/1f/Cigar_Special.jpg',
                                    0 => 'http://shopware.localhost/media/image/e5/c3/71/Cigar_Special_200x200.jpg',
                                    1 => 'http://shopware.localhost/media/image/3a/5d/7d/Cigar_Special_600x600.jpg',
                                    2 => 'http://shopware.localhost/media/image/cb/c5/15/Cigar_Special_1280x1280.jpg',
                                ],
                            'srchd' => [
                                    'original' => 'http://shopware.localhost/media/image/bf/b2/1f/Cigar_Special.jpg',
                                    0 => 'http://shopware.localhost/media/image/c3/76/c3/Cigar_Special_200x200@2x.jpg',
                                    1 => 'http://shopware.localhost/media/image/e6/c1/11/Cigar_Special_600x600@2x.jpg',
                                    2 => 'http://shopware.localhost/media/image/f3/14/54/Cigar_Special_1280x1280@2x.jpg',
                                ],
                            'res' => [
                                    'original' => [
                                            'width' => 3588,
                                            'height' => 1380,
                                        ],
                                ],
                        ],
                    'linkDetails' => 'shopware.php?sViewport=detail&sArticle=6',
                    'linkDelete' => 'shopware.php?sViewport=basket&sDelete=670',
                    'linkNote' => 'shopware.php?sViewport=note&sAdd=SW10006',
                    'tax' => '5,74',
                ],
        ],
    'Amount' => '35,95',
    'AmountNet' => '30,21',
    'Quantity' => 1,
    'AmountNumeric' => 71.939999999999998,
    'AmountNetNumeric' => 60.450000000000003,
    'AmountWithTax' => '0',
    'AmountWithTaxNumeric' => 0.0,
    'sCurrencyId' => 1,
    'sCurrencyName' => 'EUR',
    'sCurrencyFactor' => 1.0,
    'sShippingcostsWithTax' => 35.990000000000002,
    'sShippingcostsNet' => 30.239999999999998,
    'sShippingcostsTax' => 19.0,
    'sShippingcostsDifference' => 9964.0499999999993,
    'sTaxRates' => [
            '19.00' => 11.490000000000004,
        ],
    'sShippingcosts' => 35.990000000000002,
    'sAmount' => 71.939999999999998,
    'sAmountTax' => 11.49,
];
