<?php
/**
 * (c) shopware AG <info@shopware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    [
        'id' => 9998,
        'number' => '20004',
        'customerId' => 3,
        'status' => 0,
        'cleared' => 12,
        'paymentId' => 7,
        'dispatchId' => 9,
        'partnerId' => '',
        'shopId' => 1,
        'invoiceAmount' => 23.850000000000001,
        'invoiceAmountNet' => 20.039999999999999,
        'invoiceShipping' => 3.8999999999999999,
        'invoiceShippingNet' => 3.2799999999999998,
        'transactionId' => '7VM07939MN352161B',
        'comment' => '',
        'customerComment' => '',
        'internalComment' => '',
        'net' => 0,
        'taxFree' => 0,
        'temporaryId' => 'PAY-6L400934KE521913MLEFNSAI',
        'referer' => '',
        'clearedDate' => null,
        'trackingCode' => '',
        'languageIso' => '1',
        'currency' => 'EUR',
        'currencyFactor' => 1.0,
        'remoteAddress' => '127.0.0.1',
        'deviceType' => 'desktop',
        'payment' => [
            'id' => 7,
            'name' => 'SwagPaymentPayPalUnified',
            'description' => 'PayPal',
            'template' => '',
            'class' => '',
            'table' => '',
            'hide' => false,
            'additionalDescription' => 'Logo \'PayPal empfohlen\'Bezahlung per PayPal - einfach, schnell und sicher.',
            'debitPercent' => 0.0,
            'surcharge' => 0.0,
            'surchargeString' => '',
            'position' => 0,
            'active' => true,
            'esdActive' => false,
            'mobileInactive' => false,
            'embedIFrame' => '',
            'hideProspect' => 0,
            'action' => 'PaypalUnified',
            'pluginId' => null,
            'source' => null,
        ],
    ], [
        'id' => 9999,
        'number' => '20005',
        'customerId' => 3,
        'status' => 0,
        'cleared' => 12,
        'paymentId' => 7,
        'dispatchId' => 9,
        'partnerId' => '',
        'shopId' => 1,
        'invoiceAmount' => 23.850000000000001,
        'invoiceAmountNet' => 20.039999999999999,
        'invoiceShipping' => 3.8999999999999999,
        'invoiceShippingNet' => 3.2799999999999998,
        'transactionId' => '7VM07939MN352161B',
        'comment' => '',
        'customerComment' => '',
        'internalComment' => '',
        'net' => 0,
        'taxFree' => 0,
        'temporaryId' => 'PAY-6L400934KE521913MLEFNSAI',
        'referer' => '',
        'clearedDate' => null,
        'trackingCode' => '',
        'languageIso' => '1',
        'currency' => 'EUR',
        'currencyFactor' => 1.0,
        'remoteAddress' => '127.0.0.1',
        'deviceType' => 'desktop',
        'payment' => [
            'id' => 7,
            'name' => 'SwagPaymentPayPalUnified',
            'description' => 'PayPal',
            'template' => '',
            'class' => '',
            'table' => '',
            'hide' => false,
            'additionalDescription' => 'Logo \'PayPal empfohlen\'Bezahlung per PayPal - einfach, schnell und sicher.',
            'debitPercent' => 0.0,
            'surcharge' => 0.0,
            'surchargeString' => '',
            'position' => 0,
            'active' => true,
            'esdActive' => false,
            'mobileInactive' => false,
            'embedIFrame' => '',
            'hideProspect' => 0,
            'action' => 'PaypalUnified',
            'pluginId' => null,
            'source' => null,
        ],
    ],
];
