<?php
/**
 * (c) shopware AG <info@shopware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'sUserLoggedIn' => true,
    'sUserData' => [
        'billingaddress' => [
            'id' => 1,
            'company' => 'Muster GmbH',
            'department' => null,
            'salutation' => 'mr',
            'firstname' => 'Max',
            'title' => null,
            'lastname' => 'Mustermann',
            'street' => 'Musterstr. 55',
            'zipcode' => '55555',
            'city' => 'Musterhausen',
            'phone' => '05555 / 555555',
            'vatId' => null,
            'additionalAddressLine1' => null,
            'additionalAddressLine2' => null,
            'countryId' => 2,
            'stateId' => 3,
            'customer' => [
                'id' => 1,
            ],
            'country' => [
                'id' => 2,
            ],
            'state' => [
                'id' => 3,
            ],
            'userID' => 1,
            'countryID' => 2,
            'stateID' => 3,
            'ustid' => null,
            'additional_address_line1' => null,
            'additional_address_line2' => null,
        ],
        'additional' => [
            'country' => [
                'id' => '2',
                'countryname' => 'Deutschland',
                'countryiso' => 'DE',
                'areaID' => '1',
                'countryen' => 'GERMANY',
                'position' => '1',
                'notice' => '',
                'taxfree' => '0',
                'taxfree_ustid' => '0',
                'taxfree_ustid_checked' => '0',
                'active' => '1',
                'iso3' => 'DEU',
                'display_state_in_registration' => '0',
                'force_state_in_registration' => '0',
                'countryarea' => 'deutschland',
            ],
            'state' => [
                'id' => '3',
                'countryID' => '2',
                'name' => 'Nordrhein-Westfalen',
                'shortcode' => 'NW',
                'position' => '0',
                'active' => '1',
                'statename' => 'Nordrhein-Westfalen',
            ],
            'user' => [
                'id' => '1',
                'password' => '$2y$10$4ZldfTzeVlBowc1eRsTYledCOa2Yh9ta3zPVLZd4n8tL0nckZkoz2',
                'encoder' => 'bcrypt',
                'email' => 'test@example.com',
                'active' => '1',
                'accountmode' => '0',
                'confirmationkey' => '',
                'paymentID' => '5',
                'firstlogin' => '2011-11-23',
                'lastlogin' => '2017-12-18 10:26:46',
                'sessionID' => 'vgcvuepqe1e7b27gdst1k5ng74',
                'newsletter' => 0,
                'validation' => '',
                'affiliate' => '0',
                'customergroup' => 'EK',
                'paymentpreset' => '0',
                'language' => '1',
                'subshopID' => '1',
                'referer' => '',
                'pricegroupID' => null,
                'internalcomment' => '',
                'failedlogins' => '0',
                'lockeduntil' => null,
                'default_billing_address_id' => '1',
                'default_shipping_address_id' => '3',
                'title' => null,
                'salutation' => 'mr',
                'firstname' => 'Max',
                'lastname' => 'Mustermann',
                'birthday' => null,
                'customernumber' => '20001',
                'login_token' => '802970e4-f467-415c-a65a-1a445a75356a.1',
            ],
            'countryShipping' => [
                'id' => '23',
                'countryname' => 'Österreich',
                'countryiso' => 'AT',
                'areaID' => '3',
                'countryen' => 'AUSTRIA',
                'position' => '1',
                'notice' => '',
                'taxfree' => '0',
                'taxfree_ustid' => '0',
                'taxfree_ustid_checked' => '0',
                'active' => '1',
                'iso3' => 'AUT',
                'display_state_in_registration' => '0',
                'force_state_in_registration' => '0',
                'countryarea' => 'europa',
            ],
            'stateShipping' => [],
            'payment' => [
                'id' => '5',
                'name' => 'prepayment',
                'description' => 'Vorkasse',
                'template' => 'prepayment.tpl',
                'class' => 'prepayment.php',
                'table' => '',
                'hide' => '0',
                'additionaldescription' => 'Sie zahlen einfach vorab und erhalten die Ware bequem und günstig bei Zahlungseingang nach Hause geliefert.',
                'debit_percent' => '0',
                'surcharge' => '0',
                'surchargestring' => '',
                'position' => '1',
                'active' => '1',
                'esdactive' => '0',
                'embediframe' => '',
                'hideprospect' => '0',
                'action' => '',
                'pluginID' => null,
                'source' => null,
                'mobile_inactive' => '0',
                'validation' => [],
            ],
            'charge_vat' => true,
            'show_net' => true,
        ],
        'shippingaddress' => [
            'id' => 3,
            'company' => 'shopware AG',
            'department' => null,
            'salutation' => 'mr',
            'firstname' => 'Max',
            'title' => null,
            'lastname' => 'Mustermann',
            'street' => 'Mustermannstraße 92',
            'zipcode' => '48624',
            'city' => 'Schöppingen',
            'phone' => null,
            'vatId' => null,
            'additionalAddressLine1' => null,
            'additionalAddressLine2' => null,
            'countryId' => 23,
            'stateId' => null,
            'customer' => [
                'id' => 1,
            ],
            'country' => [
                'id' => 23,
            ],
            'state' => null,
            'userID' => 1,
            'countryID' => 23,
            'stateID' => null,
            'ustid' => null,
            'additional_address_line1' => null,
            'additional_address_line2' => null,
            'attributes' => [
                'id' => '1',
                'address_id' => '3',
                'text1' => null,
                'text2' => null,
                'text3' => null,
                'text4' => null,
                'text5' => null,
                'text6' => null,
            ],
        ],
    ],
    'sBasket' => [
        'content' => [
            0 => [
                'id' => '736',
                'sessionID' => 'vgcvuepqe1e7b27gdst1k5ng74',
                'userID' => '1',
                'articlename' => 'Special Finish Lagerkorn X.O. 32%',
                'articleID' => '9',
                'ordernumber' => 'SW10009',
                'shippingfree' => '0',
                'quantity' => '1',
                'price' => '24,99',
                'netprice' => '21',
                'tax_rate' => '19',
                'datum' => '2017-12-14 11:16:41',
                'modus' => '0',
                'esdarticle' => '0',
                'partnerID' => '',
                'lastviewport' => 'checkout',
                'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36',
                'config' => '',
                'currencyFactor' => '1',
                'packunit' => 'Flaschen(n)',
                'mainDetailId' => '15',
                'articleDetailId' => '15',
                'minpurchase' => '1',
                'taxID' => '1',
                'instock' => '12',
                'suppliernumber' => '',
                'maxpurchase' => '100',
                'purchasesteps' => 1,
                'purchaseunit' => '0.5000',
                'unitID' => '1',
                'laststock' => '0',
                'shippingtime' => '',
                'releasedate' => null,
                'sReleaseDate' => null,
                'ean' => null,
                'stockmin' => '0',
                'ob_attr1' => '',
                'ob_attr2' => null,
                'ob_attr3' => null,
                'ob_attr4' => null,
                'ob_attr5' => null,
                'ob_attr6' => null,
                'shippinginfo' => true,
                'esd' => '0',
                'itemUnit' => 'Liter',
                'amount' => '24,99',
                'purchaseunitTemp' => '0.5000',
                'itemInfo' => '0.5000 Liter / 24,99',
                'amountnet' => '21,00',
                'priceNumeric' => '24.99',
                'linkDetails' => 'shopware.php?sViewport=detail&sArticle=9',
                'linkDelete' => 'shopware.php?sViewport=basket&sDelete=736',
                'linkNote' => 'shopware.php?sViewport=note&sAdd=SW10009',
                'tax' => '3,99',
            ],
            1 => [
                'id' => '737',
                'sessionID' => 'vgcvuepqe1e7b27gdst1k5ng74',
                'userID' => '1',
                'articlename' => 'Münsterländer Lagerkorn 32% 0,5 Liter',
                'articleID' => '2',
                'ordernumber' => 'SW10002.3',
                'shippingfree' => '0',
                'quantity' => '1',
                'price' => '19,99',
                'netprice' => '16.798319327731',
                'tax_rate' => '19',
                'datum' => '2017-12-18 10:26:16',
                'modus' => '0',
                'esdarticle' => '0',
                'partnerID' => '',
                'lastviewport' => 'checkout',
                'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36',
                'config' => '',
                'currencyFactor' => '1',
                'packunit' => 'Flasche(n)',
                'mainDetailId' => '125',
                'articleDetailId' => '125',
                'minpurchase' => '1',
                'taxID' => '1',
                'instock' => '15',
                'suppliernumber' => '',
                'maxpurchase' => '100',
                'purchasesteps' => 1,
                'purchaseunit' => '0.5000',
                'unitID' => '1',
                'laststock' => '0',
                'shippingtime' => '',
                'releasedate' => null,
                'sReleaseDate' => null,
                'ean' => '',
                'stockmin' => '0',
                'ob_attr1' => '',
                'ob_attr2' => null,
                'ob_attr3' => null,
                'ob_attr4' => null,
                'ob_attr5' => null,
                'ob_attr6' => null,
                'shippinginfo' => true,
                'esd' => '0',
                'itemUnit' => 'Liter',
                'amount' => '19,99',
                'purchaseunitTemp' => '0.5000',
                'itemInfo' => '0.5000 Liter / 19,99',
                'amountnet' => '16,80',
                'priceNumeric' => '19.99',
                'linkDetails' => 'shopware.php?sViewport=detail&sArticle=2',
                'linkDelete' => 'shopware.php?sViewport=basket&sDelete=737',
                'linkNote' => 'shopware.php?sViewport=note&sAdd=SW10002.3',
                'tax' => '3,19',
            ],
            2 => [
                'id' => '741',
                'sessionID' => 'vgcvuepqe1e7b27gdst1k5ng74',
                'userID' => '0',
                'articlename' => 'Warenkorbrabatt',
                'articleID' => '0',
                'ordernumber' => 'SHIPPINGDISCOUNT',
                'shippingfree' => '0',
                'quantity' => '1',
                'price' => '-2,00',
                'netprice' => '-1.68',
                'tax_rate' => '19',
                'datum' => '2017-12-18 10:26:46',
                'modus' => '4',
                'esdarticle' => '0',
                'partnerID' => '',
                'lastviewport' => '',
                'useragent' => '',
                'config' => '',
                'currencyFactor' => '1',
                'packunit' => null,
                'mainDetailId' => null,
                'articleDetailId' => null,
                'minpurchase' => 1,
                'taxID' => null,
                'instock' => null,
                'suppliernumber' => null,
                'maxpurchase' => '100',
                'purchasesteps' => 1,
                'purchaseunit' => null,
                'laststock' => null,
                'shippingtime' => null,
                'releasedate' => null,
                'sReleaseDate' => null,
                'ean' => null,
                'stockmin' => null,
                'ob_attr1' => null,
                'ob_attr2' => null,
                'ob_attr3' => null,
                'ob_attr4' => null,
                'ob_attr5' => null,
                'ob_attr6' => null,
                'shippinginfo' => false,
                'esd' => '0',
                'amount' => '-2,00',
                'amountnet' => '-1,68',
                'priceNumeric' => '-2',
                'linkDetails' => 'shopware.php?sViewport=detail&sArticle=0',
                'linkDelete' => 'shopware.php?sViewport=basket&sDelete=741',
                'linkNote' => 'shopware.php?sViewport=note&sAdd=SHIPPINGDISCOUNT',
                'tax' => '-0,32',
            ],
        ],
        'Amount' => '42,98',
        'AmountNet' => '36,12',
        'Quantity' => 2,
        'AmountNumeric' => 67.969999999999999,
        'AmountNetNumeric' => 57.119999999999997,
        'AmountWithTax' => '0',
        'AmountWithTaxNumeric' => 0.0,
        'sCurrencyId' => 1,
        'sCurrencyName' => 'EUR',
        'sShippingcostsWithTax' => 24.989999999999998,
        'sShippingcostsNet' => 21.0,
        'sShippingcostsTax' => 19.0,
        'sShippingcostsDifference' => null,
        'sTaxRates' => [
            '19.00' => 10.849999999999998,
        ],
        'sShippingcosts' => 24.989999999999998,
        'sAmount' => 67.969999999999999,
        'sAmountTax' => 10.85,
    ],
];
