DROP TABLE IF EXISTS swag_payment_paypal_unified_php_unit_test_table_one;
DROP TABLE IF EXISTS swag_payment_paypal_unified_php_unit_test_table_two;
DROP TABLE IF EXISTS swag_payment_paypal_unified_php_unit_test_table_three;
DROP TABLE IF EXISTS swag_payment_paypal_unified_php_unit_test_table_four;
