TRUNCATE TABLE swag_payment_paypal_unified_payment_instruction;
TRUNCATE TABLE swag_payment_paypal_unified_settings_advanced_credit_debit_card;
TRUNCATE TABLE swag_payment_paypal_unified_settings_express;
TRUNCATE TABLE swag_payment_paypal_unified_settings_general;
TRUNCATE TABLE swag_payment_paypal_unified_settings_installments;
TRUNCATE TABLE swag_payment_paypal_unified_settings_pay_upon_invoice;
TRUNCATE TABLE swag_payment_paypal_unified_settings_plus;
